/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module SWIGTYPE_p_vtksys__hash_mapT_vtkInformationKey_p_vtkObjectBase_p_vtkInformationInternals__HashFun_t;

static import vtkd_im;

class SWIGTYPE_p_vtksys__hash_mapT_vtkInformationKey_p_vtkObjectBase_p_vtkInformationInternals__HashFun_t {
  private void* swigCPtr;

  public this(void* cObject, bool futureUse) {
    swigCPtr = cObject;
  }

  protected this() {
    swigCPtr = null;
  }

  public static void* swigGetCPtr(SWIGTYPE_p_vtksys__hash_mapT_vtkInformationKey_p_vtkObjectBase_p_vtkInformationInternals__HashFun_t obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;
}
