/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkAbstractParticleWriter;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkWriter;

class vtkAbstractParticleWriter : vtkWriter.vtkWriter {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkAbstractParticleWriter_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkAbstractParticleWriter obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkAbstractParticleWriter_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkAbstractParticleWriter SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkAbstractParticleWriter_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkAbstractParticleWriter ret = (cPtr is null) ? null : new vtkAbstractParticleWriter(cPtr, false);
    return ret;
  }

  public vtkAbstractParticleWriter NewInstance() const {
    void* cPtr = vtkd_im.vtkAbstractParticleWriter_NewInstance(cast(void*)swigCPtr);
    vtkAbstractParticleWriter ret = (cPtr is null) ? null : new vtkAbstractParticleWriter(cPtr, false);
    return ret;
  }

  alias vtkWriter.vtkWriter.NewInstance NewInstance;

  public void SetTimeStep(int _arg) {
    vtkd_im.vtkAbstractParticleWriter_SetTimeStep(cast(void*)swigCPtr, _arg);
  }

  public int GetTimeStep() {
    auto ret = vtkd_im.vtkAbstractParticleWriter_GetTimeStep(cast(void*)swigCPtr);
    return ret;
  }

  public void SetTimeValue(double _arg) {
    vtkd_im.vtkAbstractParticleWriter_SetTimeValue(cast(void*)swigCPtr, _arg);
  }

  public double GetTimeValue() {
    auto ret = vtkd_im.vtkAbstractParticleWriter_GetTimeValue(cast(void*)swigCPtr);
    return ret;
  }

  public void SetFileName(string _arg) {
    vtkd_im.vtkAbstractParticleWriter_SetFileName(cast(void*)swigCPtr, (_arg ? std.string.toStringz(_arg) : null));
  }

  public string GetFileName() {
    string ret = std.conv.to!string(vtkd_im.vtkAbstractParticleWriter_GetFileName(cast(void*)swigCPtr));
    return ret;
  }

  public void SetCollectiveIO(int _arg) {
    vtkd_im.vtkAbstractParticleWriter_SetCollectiveIO(cast(void*)swigCPtr, _arg);
  }

  public int GetCollectiveIO() {
    auto ret = vtkd_im.vtkAbstractParticleWriter_GetCollectiveIO(cast(void*)swigCPtr);
    return ret;
  }

  public void SetWriteModeToCollective() {
    vtkd_im.vtkAbstractParticleWriter_SetWriteModeToCollective(cast(void*)swigCPtr);
  }

  public void SetWriteModeToIndependent() {
    vtkd_im.vtkAbstractParticleWriter_SetWriteModeToIndependent(cast(void*)swigCPtr);
  }

  public void CloseFile() {
    vtkd_im.vtkAbstractParticleWriter_CloseFile(cast(void*)swigCPtr);
  }
}
