/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkBrownianPoints;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDataSetAlgorithm;

class vtkBrownianPoints : vtkDataSetAlgorithm.vtkDataSetAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkBrownianPoints_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkBrownianPoints obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkBrownianPoints New() {
    void* cPtr = vtkd_im.vtkBrownianPoints_New();
    vtkBrownianPoints ret = (cPtr is null) ? null : new vtkBrownianPoints(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkBrownianPoints_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkBrownianPoints SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkBrownianPoints_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkBrownianPoints ret = (cPtr is null) ? null : new vtkBrownianPoints(cPtr, false);
    return ret;
  }

  public vtkBrownianPoints NewInstance() const {
    void* cPtr = vtkd_im.vtkBrownianPoints_NewInstance(cast(void*)swigCPtr);
    vtkBrownianPoints ret = (cPtr is null) ? null : new vtkBrownianPoints(cPtr, false);
    return ret;
  }

  alias vtkDataSetAlgorithm.vtkDataSetAlgorithm.NewInstance NewInstance;

  public void SetMinimumSpeed(double _arg) {
    vtkd_im.vtkBrownianPoints_SetMinimumSpeed(cast(void*)swigCPtr, _arg);
  }

  public double GetMinimumSpeedMinValue() {
    auto ret = vtkd_im.vtkBrownianPoints_GetMinimumSpeedMinValue(cast(void*)swigCPtr);
    return ret;
  }

  public double GetMinimumSpeedMaxValue() {
    auto ret = vtkd_im.vtkBrownianPoints_GetMinimumSpeedMaxValue(cast(void*)swigCPtr);
    return ret;
  }

  public double GetMinimumSpeed() {
    auto ret = vtkd_im.vtkBrownianPoints_GetMinimumSpeed(cast(void*)swigCPtr);
    return ret;
  }

  public void SetMaximumSpeed(double _arg) {
    vtkd_im.vtkBrownianPoints_SetMaximumSpeed(cast(void*)swigCPtr, _arg);
  }

  public double GetMaximumSpeedMinValue() {
    auto ret = vtkd_im.vtkBrownianPoints_GetMaximumSpeedMinValue(cast(void*)swigCPtr);
    return ret;
  }

  public double GetMaximumSpeedMaxValue() {
    auto ret = vtkd_im.vtkBrownianPoints_GetMaximumSpeedMaxValue(cast(void*)swigCPtr);
    return ret;
  }

  public double GetMaximumSpeed() {
    auto ret = vtkd_im.vtkBrownianPoints_GetMaximumSpeed(cast(void*)swigCPtr);
    return ret;
  }
}
