/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkBase64OutputStream;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkOutputStream;

class vtkBase64OutputStream : vtkOutputStream.vtkOutputStream {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkBase64OutputStream_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkBase64OutputStream obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkBase64OutputStream_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkBase64OutputStream SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkBase64OutputStream_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkBase64OutputStream ret = (cPtr is null) ? null : new vtkBase64OutputStream(cPtr, false);
    return ret;
  }

  public vtkBase64OutputStream NewInstance() const {
    void* cPtr = vtkd_im.vtkBase64OutputStream_NewInstance(cast(void*)swigCPtr);
    vtkBase64OutputStream ret = (cPtr is null) ? null : new vtkBase64OutputStream(cPtr, false);
    return ret;
  }

  alias vtkOutputStream.vtkOutputStream.NewInstance NewInstance;

  public static vtkBase64OutputStream New() {
    void* cPtr = vtkd_im.vtkBase64OutputStream_New();
    vtkBase64OutputStream ret = (cPtr is null) ? null : new vtkBase64OutputStream(cPtr, false);
    return ret;
  }
}
