/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkBarChartActor;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDataObject;
static import vtkTextProperty;
static import SWIGTYPE_p_double;
static import vtkLegendBoxActor;
static import vtkActor2D;

class vtkBarChartActor : vtkActor2D.vtkActor2D {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkBarChartActor_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkBarChartActor obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkBarChartActor_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkBarChartActor SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkBarChartActor_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkBarChartActor ret = (cPtr is null) ? null : new vtkBarChartActor(cPtr, false);
    return ret;
  }

  public vtkBarChartActor NewInstance() const {
    void* cPtr = vtkd_im.vtkBarChartActor_NewInstance(cast(void*)swigCPtr);
    vtkBarChartActor ret = (cPtr is null) ? null : new vtkBarChartActor(cPtr, false);
    return ret;
  }

  alias vtkActor2D.vtkActor2D.NewInstance NewInstance;

  public static vtkBarChartActor New() {
    void* cPtr = vtkd_im.vtkBarChartActor_New();
    vtkBarChartActor ret = (cPtr is null) ? null : new vtkBarChartActor(cPtr, false);
    return ret;
  }

  public void SetInput(vtkDataObject.vtkDataObject arg0) {
    vtkd_im.vtkBarChartActor_SetInput(cast(void*)swigCPtr, vtkDataObject.vtkDataObject.swigGetCPtr(arg0));
  }

  public vtkDataObject.vtkDataObject GetInput() {
    void* cPtr = vtkd_im.vtkBarChartActor_GetInput(cast(void*)swigCPtr);
    vtkDataObject.vtkDataObject ret = (cPtr is null) ? null : new vtkDataObject.vtkDataObject(cPtr, false);
    return ret;
  }

  public void SetTitleVisibility(int _arg) {
    vtkd_im.vtkBarChartActor_SetTitleVisibility(cast(void*)swigCPtr, _arg);
  }

  public int GetTitleVisibility() {
    auto ret = vtkd_im.vtkBarChartActor_GetTitleVisibility(cast(void*)swigCPtr);
    return ret;
  }

  public void TitleVisibilityOn() {
    vtkd_im.vtkBarChartActor_TitleVisibilityOn(cast(void*)swigCPtr);
  }

  public void TitleVisibilityOff() {
    vtkd_im.vtkBarChartActor_TitleVisibilityOff(cast(void*)swigCPtr);
  }

  public void SetTitle(string _arg) {
    vtkd_im.vtkBarChartActor_SetTitle(cast(void*)swigCPtr, (_arg ? std.string.toStringz(_arg) : null));
  }

  public string GetTitle() {
    string ret = std.conv.to!string(vtkd_im.vtkBarChartActor_GetTitle(cast(void*)swigCPtr));
    return ret;
  }

  public void SetTitleTextProperty(vtkTextProperty.vtkTextProperty p) {
    vtkd_im.vtkBarChartActor_SetTitleTextProperty(cast(void*)swigCPtr, vtkTextProperty.vtkTextProperty.swigGetCPtr(p));
  }

  public vtkTextProperty.vtkTextProperty GetTitleTextProperty() {
    void* cPtr = vtkd_im.vtkBarChartActor_GetTitleTextProperty(cast(void*)swigCPtr);
    vtkTextProperty.vtkTextProperty ret = (cPtr is null) ? null : new vtkTextProperty.vtkTextProperty(cPtr, false);
    return ret;
  }

  public void SetLabelVisibility(int _arg) {
    vtkd_im.vtkBarChartActor_SetLabelVisibility(cast(void*)swigCPtr, _arg);
  }

  public int GetLabelVisibility() {
    auto ret = vtkd_im.vtkBarChartActor_GetLabelVisibility(cast(void*)swigCPtr);
    return ret;
  }

  public void LabelVisibilityOn() {
    vtkd_im.vtkBarChartActor_LabelVisibilityOn(cast(void*)swigCPtr);
  }

  public void LabelVisibilityOff() {
    vtkd_im.vtkBarChartActor_LabelVisibilityOff(cast(void*)swigCPtr);
  }

  public void SetLabelTextProperty(vtkTextProperty.vtkTextProperty p) {
    vtkd_im.vtkBarChartActor_SetLabelTextProperty(cast(void*)swigCPtr, vtkTextProperty.vtkTextProperty.swigGetCPtr(p));
  }

  public vtkTextProperty.vtkTextProperty GetLabelTextProperty() {
    void* cPtr = vtkd_im.vtkBarChartActor_GetLabelTextProperty(cast(void*)swigCPtr);
    vtkTextProperty.vtkTextProperty ret = (cPtr is null) ? null : new vtkTextProperty.vtkTextProperty(cPtr, false);
    return ret;
  }

  public void SetBarColor(int i, double r, double g, double b) {
    vtkd_im.vtkBarChartActor_SetBarColor__SWIG_0(cast(void*)swigCPtr, i, r, g, b);
  }

  public void SetBarColor(int i, SWIGTYPE_p_double.SWIGTYPE_p_double color) {
    vtkd_im.vtkBarChartActor_SetBarColor__SWIG_1(cast(void*)swigCPtr, i, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(color));
  }

  public double* GetBarColor(int i) {
    auto ret = cast(double*)vtkd_im.vtkBarChartActor_GetBarColor(cast(void*)swigCPtr, i);
    return ret;
  }

  public void SetBarLabel(int i, string arg1) {
    vtkd_im.vtkBarChartActor_SetBarLabel(cast(void*)swigCPtr, i, (arg1 ? std.string.toStringz(arg1) : null));
  }

  public string GetBarLabel(int i) {
    string ret = std.conv.to!string(vtkd_im.vtkBarChartActor_GetBarLabel(cast(void*)swigCPtr, i));
    return ret;
  }

  public void SetYTitle(string _arg) {
    vtkd_im.vtkBarChartActor_SetYTitle(cast(void*)swigCPtr, (_arg ? std.string.toStringz(_arg) : null));
  }

  public string GetYTitle() {
    string ret = std.conv.to!string(vtkd_im.vtkBarChartActor_GetYTitle(cast(void*)swigCPtr));
    return ret;
  }

  public void SetLegendVisibility(int _arg) {
    vtkd_im.vtkBarChartActor_SetLegendVisibility(cast(void*)swigCPtr, _arg);
  }

  public int GetLegendVisibility() {
    auto ret = vtkd_im.vtkBarChartActor_GetLegendVisibility(cast(void*)swigCPtr);
    return ret;
  }

  public void LegendVisibilityOn() {
    vtkd_im.vtkBarChartActor_LegendVisibilityOn(cast(void*)swigCPtr);
  }

  public void LegendVisibilityOff() {
    vtkd_im.vtkBarChartActor_LegendVisibilityOff(cast(void*)swigCPtr);
  }

  public vtkLegendBoxActor.vtkLegendBoxActor GetLegendActor() {
    void* cPtr = vtkd_im.vtkBarChartActor_GetLegendActor(cast(void*)swigCPtr);
    vtkLegendBoxActor.vtkLegendBoxActor ret = (cPtr is null) ? null : new vtkLegendBoxActor.vtkLegendBoxActor(cPtr, false);
    return ret;
  }
}
