/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkCharTuple9TN;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;

class vtkCharTuple9TN {
  private void* swigCPtr;
  protected bool swigCMemOwn;

  public this(void* cObject, bool ownCObject) {
    swigCPtr = cObject;
    swigCMemOwn = ownCObject;
  }

  public static void* swigGetCPtr(vtkCharTuple9TN obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkCharTuple9TN(cast(void*)swigCPtr);
        }
        swigCPtr = null;
      }
    }
  }

  public this() {
    this(vtkd_im.new_vtkCharTuple9TN__SWIG_0(), true);
  }

  public this(char scalar) {
    this(vtkd_im.new_vtkCharTuple9TN__SWIG_1(scalar), true);
  }

  public this(string init) {
    this(vtkd_im.new_vtkCharTuple9TN__SWIG_2((init ? std.string.toStringz(init) : null)), true);
  }

  public int GetSize() const {
    auto ret = vtkd_im.vtkCharTuple9TN_GetSize(cast(void*)swigCPtr);
    return ret;
  }

  public string GetData() {
    string ret = std.conv.to!string(vtkd_im.vtkCharTuple9TN_GetData__SWIG_0(cast(void*)swigCPtr));
    return ret;
  }

  public char* opIndex(int i) {
    auto ret = cast(char*)vtkd_im.vtkCharTuple9TN_opIndex__SWIG_0(cast(void*)swigCPtr, i);
    return ret;
  }

  public char opCall(int i) const {
    auto ret = vtkd_im.vtkCharTuple9TN_opCall(cast(void*)swigCPtr, i);
    return ret;
  }

  public bool Compare(vtkCharTuple9TN other, char tol) const {
    bool ret = vtkd_im.vtkCharTuple9TN_Compare(cast(void*)swigCPtr, vtkCharTuple9TN.swigGetCPtr(other), tol) ? true : false;
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
    return ret;
  }
}
