/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkConvertSelectionDomain;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkPassInputTypeAlgorithm;

class vtkConvertSelectionDomain : vtkPassInputTypeAlgorithm.vtkPassInputTypeAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkConvertSelectionDomain_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkConvertSelectionDomain obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkConvertSelectionDomain New() {
    void* cPtr = vtkd_im.vtkConvertSelectionDomain_New();
    vtkConvertSelectionDomain ret = (cPtr is null) ? null : new vtkConvertSelectionDomain(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkConvertSelectionDomain_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkConvertSelectionDomain SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkConvertSelectionDomain_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkConvertSelectionDomain ret = (cPtr is null) ? null : new vtkConvertSelectionDomain(cPtr, false);
    return ret;
  }

  public vtkConvertSelectionDomain NewInstance() const {
    void* cPtr = vtkd_im.vtkConvertSelectionDomain_NewInstance(cast(void*)swigCPtr);
    vtkConvertSelectionDomain ret = (cPtr is null) ? null : new vtkConvertSelectionDomain(cPtr, false);
    return ret;
  }

  alias vtkPassInputTypeAlgorithm.vtkPassInputTypeAlgorithm.NewInstance NewInstance;
}
