/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkCameraPass;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkRenderPass;

class vtkCameraPass : vtkRenderPass.vtkRenderPass {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkCameraPass_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkCameraPass obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkCameraPass New() {
    void* cPtr = vtkd_im.vtkCameraPass_New();
    vtkCameraPass ret = (cPtr is null) ? null : new vtkCameraPass(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkCameraPass_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkCameraPass SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkCameraPass_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkCameraPass ret = (cPtr is null) ? null : new vtkCameraPass(cPtr, false);
    return ret;
  }

  public vtkCameraPass NewInstance() const {
    void* cPtr = vtkd_im.vtkCameraPass_NewInstance(cast(void*)swigCPtr);
    vtkCameraPass ret = (cPtr is null) ? null : new vtkCameraPass(cPtr, false);
    return ret;
  }

  alias vtkRenderPass.vtkRenderPass.NewInstance NewInstance;

  public vtkRenderPass.vtkRenderPass GetDelegatePass() {
    void* cPtr = vtkd_im.vtkCameraPass_GetDelegatePass(cast(void*)swigCPtr);
    vtkRenderPass.vtkRenderPass ret = (cPtr is null) ? null : new vtkRenderPass.vtkRenderPass(cPtr, false);
    return ret;
  }

  public void SetDelegatePass(vtkRenderPass.vtkRenderPass delegatePass) {
    vtkd_im.vtkCameraPass_SetDelegatePass(cast(void*)swigCPtr, vtkRenderPass.vtkRenderPass.swigGetCPtr(delegatePass));
  }

  public void SetAspectRatioOverride(double _arg) {
    vtkd_im.vtkCameraPass_SetAspectRatioOverride(cast(void*)swigCPtr, _arg);
  }

  public double GetAspectRatioOverride() {
    auto ret = vtkd_im.vtkCameraPass_GetAspectRatioOverride(cast(void*)swigCPtr);
    return ret;
  }
}
