/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkColor3d;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkColor3DoubleT;

class vtkColor3d : vtkColor3DoubleT.vtkColor3DoubleT {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkColor3d_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkColor3d obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkColor3d(cast(void*)swigCPtr);
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public this() {
    this(vtkd_im.new_vtkColor3d__SWIG_0(), true);
  }

  public this(double scalar) {
    this(vtkd_im.new_vtkColor3d__SWIG_1(scalar), true);
  }

  public this(double* init) {
    this(vtkd_im.new_vtkColor3d__SWIG_2(cast(void*)init), true);
  }

  public this(double r, double g, double b) {
    this(vtkd_im.new_vtkColor3d__SWIG_3(r, g, b), true);
  }
}
