/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkColor4CharT;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkCharTuple4TN;

class vtkColor4CharT : vtkCharTuple4TN.vtkCharTuple4TN {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkColor4CharT_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkColor4CharT obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkColor4CharT(cast(void*)swigCPtr);
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public this() {
    this(vtkd_im.new_vtkColor4CharT__SWIG_0(), true);
  }

  public this(char scalar) {
    this(vtkd_im.new_vtkColor4CharT__SWIG_1(scalar), true);
  }

  public this(string init) {
    this(vtkd_im.new_vtkColor4CharT__SWIG_2((init ? std.string.toStringz(init) : null)), true);
  }

  public this(char red, char green, char blue, char alpha) {
    this(vtkd_im.new_vtkColor4CharT__SWIG_3(red, green, blue, alpha), true);
  }

  public void Set(char red, char green, char blue) {
    vtkd_im.vtkColor4CharT_Set__SWIG_0(cast(void*)swigCPtr, red, green, blue);
  }

  public void Set(char red, char green, char blue, char alpha) {
    vtkd_im.vtkColor4CharT_Set__SWIG_1(cast(void*)swigCPtr, red, green, blue, alpha);
  }

  public void SetRed(char red) {
    vtkd_im.vtkColor4CharT_SetRed(cast(void*)swigCPtr, red);
  }

  public char GetRed() const {
    auto ret = vtkd_im.vtkColor4CharT_GetRed(cast(void*)swigCPtr);
    return ret;
  }

  public void SetGreen(char green) {
    vtkd_im.vtkColor4CharT_SetGreen(cast(void*)swigCPtr, green);
  }

  public char GetGreen() const {
    auto ret = vtkd_im.vtkColor4CharT_GetGreen(cast(void*)swigCPtr);
    return ret;
  }

  public void SetBlue(char blue) {
    vtkd_im.vtkColor4CharT_SetBlue(cast(void*)swigCPtr, blue);
  }

  public char GetBlue() const {
    auto ret = vtkd_im.vtkColor4CharT_GetBlue(cast(void*)swigCPtr);
    return ret;
  }

  public void SetAlpha(char alpha) {
    vtkd_im.vtkColor4CharT_SetAlpha(cast(void*)swigCPtr, alpha);
  }

  public char GetAlpha() const {
    auto ret = vtkd_im.vtkColor4CharT_GetAlpha(cast(void*)swigCPtr);
    return ret;
  }

  public char Red() const {
    auto ret = vtkd_im.vtkColor4CharT_Red(cast(void*)swigCPtr);
    return ret;
  }

  public char Green() const {
    auto ret = vtkd_im.vtkColor4CharT_Green(cast(void*)swigCPtr);
    return ret;
  }

  public char Blue() const {
    auto ret = vtkd_im.vtkColor4CharT_Blue(cast(void*)swigCPtr);
    return ret;
  }

  public char Alpha() const {
    auto ret = vtkd_im.vtkColor4CharT_Alpha(cast(void*)swigCPtr);
    return ret;
  }
}
