/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkContextView;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkContext2D;
static import vtkContextScene;
static import vtkRenderViewBase;

class vtkContextView : vtkRenderViewBase.vtkRenderViewBase {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkContextView_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkContextView obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkContextView_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkContextView SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkContextView_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkContextView ret = (cPtr is null) ? null : new vtkContextView(cPtr, false);
    return ret;
  }

  public vtkContextView NewInstance() const {
    void* cPtr = vtkd_im.vtkContextView_NewInstance(cast(void*)swigCPtr);
    vtkContextView ret = (cPtr is null) ? null : new vtkContextView(cPtr, false);
    return ret;
  }

  alias vtkRenderViewBase.vtkRenderViewBase.NewInstance NewInstance;

  public static vtkContextView New() {
    void* cPtr = vtkd_im.vtkContextView_New();
    vtkContextView ret = (cPtr is null) ? null : new vtkContextView(cPtr, false);
    return ret;
  }

  public void SetContext(vtkContext2D.vtkContext2D context) {
    vtkd_im.vtkContextView_SetContext(cast(void*)swigCPtr, vtkContext2D.vtkContext2D.swigGetCPtr(context));
  }

  public vtkContext2D.vtkContext2D GetContext() {
    void* cPtr = vtkd_im.vtkContextView_GetContext(cast(void*)swigCPtr);
    vtkContext2D.vtkContext2D ret = (cPtr is null) ? null : new vtkContext2D.vtkContext2D(cPtr, false);
    return ret;
  }

  public void SetScene(vtkContextScene.vtkContextScene scene) {
    vtkd_im.vtkContextView_SetScene(cast(void*)swigCPtr, vtkContextScene.vtkContextScene.swigGetCPtr(scene));
  }

  public vtkContextScene.vtkContextScene GetScene() {
    void* cPtr = vtkd_im.vtkContextView_GetScene(cast(void*)swigCPtr);
    vtkContextScene.vtkContextScene ret = (cPtr is null) ? null : new vtkContextScene.vtkContextScene(cPtr, false);
    return ret;
  }
}
