/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkCirclePackToPolyData;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkInformation;
static import vtkPolyDataAlgorithm;

class vtkCirclePackToPolyData : vtkPolyDataAlgorithm.vtkPolyDataAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkCirclePackToPolyData_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkCirclePackToPolyData obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkCirclePackToPolyData New() {
    void* cPtr = vtkd_im.vtkCirclePackToPolyData_New();
    vtkCirclePackToPolyData ret = (cPtr is null) ? null : new vtkCirclePackToPolyData(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkCirclePackToPolyData_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkCirclePackToPolyData SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkCirclePackToPolyData_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkCirclePackToPolyData ret = (cPtr is null) ? null : new vtkCirclePackToPolyData(cPtr, false);
    return ret;
  }

  public vtkCirclePackToPolyData NewInstance() const {
    void* cPtr = vtkd_im.vtkCirclePackToPolyData_NewInstance(cast(void*)swigCPtr);
    vtkCirclePackToPolyData ret = (cPtr is null) ? null : new vtkCirclePackToPolyData(cPtr, false);
    return ret;
  }

  alias vtkPolyDataAlgorithm.vtkPolyDataAlgorithm.NewInstance NewInstance;

  public void SetCirclesArrayName(string name) {
    vtkd_im.vtkCirclePackToPolyData_SetCirclesArrayName(cast(void*)swigCPtr, (name ? std.string.toStringz(name) : null));
  }

  public void SetResolution(uint _arg) {
    vtkd_im.vtkCirclePackToPolyData_SetResolution(cast(void*)swigCPtr, _arg);
  }

  public uint GetResolution() {
    auto ret = vtkd_im.vtkCirclePackToPolyData_GetResolution(cast(void*)swigCPtr);
    return ret;
  }

  public int FillInputPortInformation(int port, vtkInformation.vtkInformation info) {
    auto ret = vtkd_im.vtkCirclePackToPolyData_FillInputPortInformation(cast(void*)swigCPtr, port, vtkInformation.vtkInformation.swigGetCPtr(info));
    return ret;
  }
}
