/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkDoubleVector2T;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkDoubleVector2TN;

class vtkDoubleVector2T : vtkDoubleVector2TN.vtkDoubleVector2TN {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkDoubleVector2T_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkDoubleVector2T obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkDoubleVector2T(cast(void*)swigCPtr);
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public this() {
    this(vtkd_im.new_vtkDoubleVector2T__SWIG_0(), true);
  }

  public this(double scalar) {
    this(vtkd_im.new_vtkDoubleVector2T__SWIG_1(scalar), true);
  }

  public this(double* init) {
    this(vtkd_im.new_vtkDoubleVector2T__SWIG_2(cast(void*)init), true);
  }

  public this(double x, double y) {
    this(vtkd_im.new_vtkDoubleVector2T__SWIG_3(x, y), true);
  }

  public void Set(double x, double y) {
    vtkd_im.vtkDoubleVector2T_Set(cast(void*)swigCPtr, x, y);
  }

  public void SetX(double x) {
    vtkd_im.vtkDoubleVector2T_SetX(cast(void*)swigCPtr, x);
  }

  public double GetX() const {
    auto ret = vtkd_im.vtkDoubleVector2T_GetX(cast(void*)swigCPtr);
    return ret;
  }

  public void SetY(double y) {
    vtkd_im.vtkDoubleVector2T_SetY(cast(void*)swigCPtr, y);
  }

  public double GetY() const {
    auto ret = vtkd_im.vtkDoubleVector2T_GetY(cast(void*)swigCPtr);
    return ret;
  }

  public double X() const {
    auto ret = vtkd_im.vtkDoubleVector2T_X(cast(void*)swigCPtr);
    return ret;
  }

  public double Y() const {
    auto ret = vtkd_im.vtkDoubleVector2T_Y(cast(void*)swigCPtr);
    return ret;
  }
}
