/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkDataSetAlgorithm;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDataSet;
static import vtkDataObject;
static import vtkPolyData;
static import vtkStructuredPoints;
static import vtkImageData;
static import vtkStructuredGrid;
static import vtkUnstructuredGrid;
static import vtkRectilinearGrid;
static import vtkAlgorithm;

class vtkDataSetAlgorithm : vtkAlgorithm.vtkAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkDataSetAlgorithm_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkDataSetAlgorithm obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkDataSetAlgorithm New() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_New();
    vtkDataSetAlgorithm ret = (cPtr is null) ? null : new vtkDataSetAlgorithm(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkDataSetAlgorithm_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkDataSetAlgorithm SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkDataSetAlgorithm ret = (cPtr is null) ? null : new vtkDataSetAlgorithm(cPtr, false);
    return ret;
  }

  public vtkDataSetAlgorithm NewInstance() const {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_NewInstance(cast(void*)swigCPtr);
    vtkDataSetAlgorithm ret = (cPtr is null) ? null : new vtkDataSetAlgorithm(cPtr, false);
    return ret;
  }

  alias vtkAlgorithm.vtkAlgorithm.NewInstance NewInstance;

  public vtkDataSet.vtkDataSet GetOutput() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetOutput__SWIG_0(cast(void*)swigCPtr);
    vtkDataSet.vtkDataSet ret = (cPtr is null) ? null : new vtkDataSet.vtkDataSet(cPtr, false);
    return ret;
  }

  public vtkDataSet.vtkDataSet GetOutput(int arg0) {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetOutput__SWIG_1(cast(void*)swigCPtr, arg0);
    vtkDataSet.vtkDataSet ret = (cPtr is null) ? null : new vtkDataSet.vtkDataSet(cPtr, false);
    return ret;
  }

  public vtkDataObject.vtkDataObject GetInput() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetInput(cast(void*)swigCPtr);
    vtkDataObject.vtkDataObject ret = (cPtr is null) ? null : new vtkDataObject.vtkDataObject(cPtr, false);
    return ret;
  }

  public vtkPolyData.vtkPolyData GetPolyDataOutput() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetPolyDataOutput(cast(void*)swigCPtr);
    vtkPolyData.vtkPolyData ret = (cPtr is null) ? null : new vtkPolyData.vtkPolyData(cPtr, false);
    return ret;
  }

  public vtkStructuredPoints.vtkStructuredPoints GetStructuredPointsOutput() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetStructuredPointsOutput(cast(void*)swigCPtr);
    vtkStructuredPoints.vtkStructuredPoints ret = (cPtr is null) ? null : new vtkStructuredPoints.vtkStructuredPoints(cPtr, false);
    return ret;
  }

  public vtkImageData.vtkImageData GetImageDataOutput() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetImageDataOutput(cast(void*)swigCPtr);
    vtkImageData.vtkImageData ret = (cPtr is null) ? null : new vtkImageData.vtkImageData(cPtr, false);
    return ret;
  }

  public vtkStructuredGrid.vtkStructuredGrid GetStructuredGridOutput() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetStructuredGridOutput(cast(void*)swigCPtr);
    vtkStructuredGrid.vtkStructuredGrid ret = (cPtr is null) ? null : new vtkStructuredGrid.vtkStructuredGrid(cPtr, false);
    return ret;
  }

  public vtkUnstructuredGrid.vtkUnstructuredGrid GetUnstructuredGridOutput() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetUnstructuredGridOutput(cast(void*)swigCPtr);
    vtkUnstructuredGrid.vtkUnstructuredGrid ret = (cPtr is null) ? null : new vtkUnstructuredGrid.vtkUnstructuredGrid(cPtr, false);
    return ret;
  }

  public vtkRectilinearGrid.vtkRectilinearGrid GetRectilinearGridOutput() {
    void* cPtr = vtkd_im.vtkDataSetAlgorithm_GetRectilinearGridOutput(cast(void*)swigCPtr);
    vtkRectilinearGrid.vtkRectilinearGrid ret = (cPtr is null) ? null : new vtkRectilinearGrid.vtkRectilinearGrid(cPtr, false);
    return ret;
  }

  public void SetInputData(vtkDataObject.vtkDataObject arg0) {
    vtkd_im.vtkDataSetAlgorithm_SetInputData__SWIG_0(cast(void*)swigCPtr, vtkDataObject.vtkDataObject.swigGetCPtr(arg0));
  }

  public void SetInputData(int arg0, vtkDataObject.vtkDataObject arg1) {
    vtkd_im.vtkDataSetAlgorithm_SetInputData__SWIG_1(cast(void*)swigCPtr, arg0, vtkDataObject.vtkDataObject.swigGetCPtr(arg1));
  }

  public void SetInputData(vtkDataSet.vtkDataSet arg0) {
    vtkd_im.vtkDataSetAlgorithm_SetInputData__SWIG_2(cast(void*)swigCPtr, vtkDataSet.vtkDataSet.swigGetCPtr(arg0));
  }

  public void SetInputData(int arg0, vtkDataSet.vtkDataSet arg1) {
    vtkd_im.vtkDataSetAlgorithm_SetInputData__SWIG_3(cast(void*)swigCPtr, arg0, vtkDataSet.vtkDataSet.swigGetCPtr(arg1));
  }

  public void AddInputData(vtkDataObject.vtkDataObject arg0) {
    vtkd_im.vtkDataSetAlgorithm_AddInputData__SWIG_0(cast(void*)swigCPtr, vtkDataObject.vtkDataObject.swigGetCPtr(arg0));
  }

  public void AddInputData(vtkDataSet.vtkDataSet arg0) {
    vtkd_im.vtkDataSetAlgorithm_AddInputData__SWIG_1(cast(void*)swigCPtr, vtkDataSet.vtkDataSet.swigGetCPtr(arg0));
  }

  public void AddInputData(int arg0, vtkDataSet.vtkDataSet arg1) {
    vtkd_im.vtkDataSetAlgorithm_AddInputData__SWIG_2(cast(void*)swigCPtr, arg0, vtkDataSet.vtkDataSet.swigGetCPtr(arg1));
  }

  public void AddInputData(int arg0, vtkDataObject.vtkDataObject arg1) {
    vtkd_im.vtkDataSetAlgorithm_AddInputData__SWIG_3(cast(void*)swigCPtr, arg0, vtkDataObject.vtkDataObject.swigGetCPtr(arg1));
  }
}
