/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkDataArrayCollectionIterator;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkCollection;
static import vtkDataArrayCollection;
static import vtkDataArray;
static import vtkCollectionIterator;

class vtkDataArrayCollectionIterator : vtkCollectionIterator.vtkCollectionIterator {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkDataArrayCollectionIterator_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkDataArrayCollectionIterator obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkDataArrayCollectionIterator_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkDataArrayCollectionIterator SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkDataArrayCollectionIterator_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkDataArrayCollectionIterator ret = (cPtr is null) ? null : new vtkDataArrayCollectionIterator(cPtr, false);
    return ret;
  }

  public vtkDataArrayCollectionIterator NewInstance() const {
    void* cPtr = vtkd_im.vtkDataArrayCollectionIterator_NewInstance(cast(void*)swigCPtr);
    vtkDataArrayCollectionIterator ret = (cPtr is null) ? null : new vtkDataArrayCollectionIterator(cPtr, false);
    return ret;
  }

  alias vtkCollectionIterator.vtkCollectionIterator.NewInstance NewInstance;

  public static vtkDataArrayCollectionIterator New() {
    void* cPtr = vtkd_im.vtkDataArrayCollectionIterator_New();
    vtkDataArrayCollectionIterator ret = (cPtr is null) ? null : new vtkDataArrayCollectionIterator(cPtr, false);
    return ret;
  }

  public override void SetCollection(vtkCollection.vtkCollection arg0) {
    vtkd_im.vtkDataArrayCollectionIterator_SetCollection__SWIG_0(cast(void*)swigCPtr, vtkCollection.vtkCollection.swigGetCPtr(arg0));
  }

  public void SetCollection(vtkDataArrayCollection.vtkDataArrayCollection arg0) {
    vtkd_im.vtkDataArrayCollectionIterator_SetCollection__SWIG_1(cast(void*)swigCPtr, vtkDataArrayCollection.vtkDataArrayCollection.swigGetCPtr(arg0));
  }

  alias vtkCollectionIterator.vtkCollectionIterator.SetCollection SetCollection;

  public vtkDataArray.vtkDataArray GetDataArray() {
    void* cPtr = vtkd_im.vtkDataArrayCollectionIterator_GetDataArray(cast(void*)swigCPtr);
    vtkDataArray.vtkDataArray ret = (cPtr is null) ? null : new vtkDataArray.vtkDataArray(cPtr, false);
    return ret;
  }
}
