/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkExtractSelectedThresholds;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDataArray;
static import vtkExtractSelectionBase;

class vtkExtractSelectedThresholds : vtkExtractSelectionBase.vtkExtractSelectionBase {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkExtractSelectedThresholds_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkExtractSelectedThresholds obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkExtractSelectedThresholds_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkExtractSelectedThresholds SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkExtractSelectedThresholds_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkExtractSelectedThresholds ret = (cPtr is null) ? null : new vtkExtractSelectedThresholds(cPtr, false);
    return ret;
  }

  public vtkExtractSelectedThresholds NewInstance() const {
    void* cPtr = vtkd_im.vtkExtractSelectedThresholds_NewInstance(cast(void*)swigCPtr);
    vtkExtractSelectedThresholds ret = (cPtr is null) ? null : new vtkExtractSelectedThresholds(cPtr, false);
    return ret;
  }

  alias vtkExtractSelectionBase.vtkExtractSelectionBase.NewInstance NewInstance;

  public static vtkExtractSelectedThresholds New() {
    void* cPtr = vtkd_im.vtkExtractSelectedThresholds_New();
    vtkExtractSelectedThresholds ret = (cPtr is null) ? null : new vtkExtractSelectedThresholds(cPtr, false);
    return ret;
  }

  public static int EvaluateValue(vtkDataArray.vtkDataArray scalars, long id, vtkDataArray.vtkDataArray lims) {
    auto ret = vtkd_im.vtkExtractSelectedThresholds_EvaluateValue__SWIG_0(vtkDataArray.vtkDataArray.swigGetCPtr(scalars), id, vtkDataArray.vtkDataArray.swigGetCPtr(lims));
    return ret;
  }

  public static int EvaluateValue(vtkDataArray.vtkDataArray array, int array_component_no, long id, vtkDataArray.vtkDataArray lims) {
    auto ret = vtkd_im.vtkExtractSelectedThresholds_EvaluateValue__SWIG_1(vtkDataArray.vtkDataArray.swigGetCPtr(array), array_component_no, id, vtkDataArray.vtkDataArray.swigGetCPtr(lims));
    return ret;
  }

  public static int EvaluateValue(vtkDataArray.vtkDataArray scalars, long id, vtkDataArray.vtkDataArray lims, int* AboveCount, int* BelowCount, int* InsideCount) {
    auto ret = vtkd_im.vtkExtractSelectedThresholds_EvaluateValue__SWIG_2(vtkDataArray.vtkDataArray.swigGetCPtr(scalars), id, vtkDataArray.vtkDataArray.swigGetCPtr(lims), cast(void*)AboveCount, cast(void*)BelowCount, cast(void*)InsideCount);
    return ret;
  }

  public static int EvaluateValue(vtkDataArray.vtkDataArray scalars, int array_component_no, long id, vtkDataArray.vtkDataArray lims, int* AboveCount, int* BelowCount, int* InsideCount) {
    auto ret = vtkd_im.vtkExtractSelectedThresholds_EvaluateValue__SWIG_3(vtkDataArray.vtkDataArray.swigGetCPtr(scalars), array_component_no, id, vtkDataArray.vtkDataArray.swigGetCPtr(lims), cast(void*)AboveCount, cast(void*)BelowCount, cast(void*)InsideCount);
    return ret;
  }
}
