/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkGlyph2D;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkGlyph3D;

class vtkGlyph2D : vtkGlyph3D.vtkGlyph3D {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkGlyph2D_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkGlyph2D obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkGlyph2D_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkGlyph2D SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkGlyph2D_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkGlyph2D ret = (cPtr is null) ? null : new vtkGlyph2D(cPtr, false);
    return ret;
  }

  public vtkGlyph2D NewInstance() const {
    void* cPtr = vtkd_im.vtkGlyph2D_NewInstance(cast(void*)swigCPtr);
    vtkGlyph2D ret = (cPtr is null) ? null : new vtkGlyph2D(cPtr, false);
    return ret;
  }

  alias vtkGlyph3D.vtkGlyph3D.NewInstance NewInstance;

  public static vtkGlyph2D New() {
    void* cPtr = vtkd_im.vtkGlyph2D_New();
    vtkGlyph2D ret = (cPtr is null) ? null : new vtkGlyph2D(cPtr, false);
    return ret;
  }
}
