/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkGlobFileNames;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkStringArray;
static import vtkObject;

class vtkGlobFileNames : vtkObject.vtkObject {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkGlobFileNames_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkGlobFileNames obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkGlobFileNames_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkGlobFileNames SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkGlobFileNames_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkGlobFileNames ret = (cPtr is null) ? null : new vtkGlobFileNames(cPtr, false);
    return ret;
  }

  public vtkGlobFileNames NewInstance() const {
    void* cPtr = vtkd_im.vtkGlobFileNames_NewInstance(cast(void*)swigCPtr);
    vtkGlobFileNames ret = (cPtr is null) ? null : new vtkGlobFileNames(cPtr, false);
    return ret;
  }

  alias vtkObject.vtkObject.NewInstance NewInstance;

  public static vtkGlobFileNames New() {
    void* cPtr = vtkd_im.vtkGlobFileNames_New();
    vtkGlobFileNames ret = (cPtr is null) ? null : new vtkGlobFileNames(cPtr, false);
    return ret;
  }

  public void Reset() {
    vtkd_im.vtkGlobFileNames_Reset(cast(void*)swigCPtr);
  }

  public void SetDirectory(string _arg) {
    vtkd_im.vtkGlobFileNames_SetDirectory(cast(void*)swigCPtr, (_arg ? std.string.toStringz(_arg) : null));
  }

  public string GetDirectory() {
    string ret = std.conv.to!string(vtkd_im.vtkGlobFileNames_GetDirectory(cast(void*)swigCPtr));
    return ret;
  }

  public int AddFileNames(string pattern) {
    auto ret = vtkd_im.vtkGlobFileNames_AddFileNames(cast(void*)swigCPtr, (pattern ? std.string.toStringz(pattern) : null));
    return ret;
  }

  public void SetRecurse(int _arg) {
    vtkd_im.vtkGlobFileNames_SetRecurse(cast(void*)swigCPtr, _arg);
  }

  public void RecurseOn() {
    vtkd_im.vtkGlobFileNames_RecurseOn(cast(void*)swigCPtr);
  }

  public void RecurseOff() {
    vtkd_im.vtkGlobFileNames_RecurseOff(cast(void*)swigCPtr);
  }

  public int GetRecurse() {
    auto ret = vtkd_im.vtkGlobFileNames_GetRecurse(cast(void*)swigCPtr);
    return ret;
  }

  public int GetNumberOfFileNames() {
    auto ret = vtkd_im.vtkGlobFileNames_GetNumberOfFileNames(cast(void*)swigCPtr);
    return ret;
  }

  public string GetNthFileName(int index) {
    string ret = std.conv.to!string(vtkd_im.vtkGlobFileNames_GetNthFileName(cast(void*)swigCPtr, index));
    return ret;
  }

  public vtkStringArray.vtkStringArray GetFileNames() {
    void* cPtr = vtkd_im.vtkGlobFileNames_GetFileNames(cast(void*)swigCPtr);
    vtkStringArray.vtkStringArray ret = (cPtr is null) ? null : new vtkStringArray.vtkStringArray(cPtr, false);
    return ret;
  }
}
