/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkImageCorrelation;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDataObject;
static import vtkThreadedImageAlgorithm;

class vtkImageCorrelation : vtkThreadedImageAlgorithm.vtkThreadedImageAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkImageCorrelation_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkImageCorrelation obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkImageCorrelation New() {
    void* cPtr = vtkd_im.vtkImageCorrelation_New();
    vtkImageCorrelation ret = (cPtr is null) ? null : new vtkImageCorrelation(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkImageCorrelation_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkImageCorrelation SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkImageCorrelation_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkImageCorrelation ret = (cPtr is null) ? null : new vtkImageCorrelation(cPtr, false);
    return ret;
  }

  public vtkImageCorrelation NewInstance() const {
    void* cPtr = vtkd_im.vtkImageCorrelation_NewInstance(cast(void*)swigCPtr);
    vtkImageCorrelation ret = (cPtr is null) ? null : new vtkImageCorrelation(cPtr, false);
    return ret;
  }

  alias vtkThreadedImageAlgorithm.vtkThreadedImageAlgorithm.NewInstance NewInstance;

  public void SetDimensionality(int _arg) {
    vtkd_im.vtkImageCorrelation_SetDimensionality(cast(void*)swigCPtr, _arg);
  }

  public int GetDimensionalityMinValue() {
    auto ret = vtkd_im.vtkImageCorrelation_GetDimensionalityMinValue(cast(void*)swigCPtr);
    return ret;
  }

  public int GetDimensionalityMaxValue() {
    auto ret = vtkd_im.vtkImageCorrelation_GetDimensionalityMaxValue(cast(void*)swigCPtr);
    return ret;
  }

  public int GetDimensionality() {
    auto ret = vtkd_im.vtkImageCorrelation_GetDimensionality(cast(void*)swigCPtr);
    return ret;
  }

  public void SetInput1Data(vtkDataObject.vtkDataObject arg0) {
    vtkd_im.vtkImageCorrelation_SetInput1Data(cast(void*)swigCPtr, vtkDataObject.vtkDataObject.swigGetCPtr(arg0));
  }

  public void SetInput2Data(vtkDataObject.vtkDataObject arg0) {
    vtkd_im.vtkImageCorrelation_SetInput2Data(cast(void*)swigCPtr, vtkDataObject.vtkDataObject.swigGetCPtr(arg0));
  }
}
