/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkOutputStream;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkObject;

class vtkOutputStream : vtkObject.vtkObject {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkOutputStream_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkOutputStream obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkOutputStream_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkOutputStream SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkOutputStream_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkOutputStream ret = (cPtr is null) ? null : new vtkOutputStream(cPtr, false);
    return ret;
  }

  public vtkOutputStream NewInstance() const {
    void* cPtr = vtkd_im.vtkOutputStream_NewInstance(cast(void*)swigCPtr);
    vtkOutputStream ret = (cPtr is null) ? null : new vtkOutputStream(cPtr, false);
    return ret;
  }

  alias vtkObject.vtkObject.NewInstance NewInstance;

  public static vtkOutputStream New() {
    void* cPtr = vtkd_im.vtkOutputStream_New();
    vtkOutputStream ret = (cPtr is null) ? null : new vtkOutputStream(cPtr, false);
    return ret;
  }

  public int StartWriting() {
    auto ret = vtkd_im.vtkOutputStream_StartWriting(cast(void*)swigCPtr);
    return ret;
  }

  public int Write(void* data, size_t length) {
    auto ret = vtkd_im.vtkOutputStream_Write(cast(void*)swigCPtr, cast(void*)data, length);
    return ret;
  }

  public int EndWriting() {
    auto ret = vtkd_im.vtkOutputStream_EndWriting(cast(void*)swigCPtr);
    return ret;
  }
}
