/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkPointData;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDataSetAttributes;

class vtkPointData : vtkDataSetAttributes.vtkDataSetAttributes {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkPointData_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkPointData obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkPointData New() {
    void* cPtr = vtkd_im.vtkPointData_New();
    vtkPointData ret = (cPtr is null) ? null : new vtkPointData(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkPointData_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkPointData SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkPointData_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkPointData ret = (cPtr is null) ? null : new vtkPointData(cPtr, false);
    return ret;
  }

  public vtkPointData NewInstance() const {
    void* cPtr = vtkd_im.vtkPointData_NewInstance(cast(void*)swigCPtr);
    vtkPointData ret = (cPtr is null) ? null : new vtkPointData(cPtr, false);
    return ret;
  }

  alias vtkDataSetAttributes.vtkDataSetAttributes.NewInstance NewInstance;

  public void NullPoint(long ptId) {
    vtkd_im.vtkPointData_NullPoint(cast(void*)swigCPtr, ptId);
  }
}
