/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkPlot3DMetaReader;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkMultiBlockDataSetAlgorithm;

class vtkPlot3DMetaReader : vtkMultiBlockDataSetAlgorithm.vtkMultiBlockDataSetAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkPlot3DMetaReader_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkPlot3DMetaReader obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkPlot3DMetaReader New() {
    void* cPtr = vtkd_im.vtkPlot3DMetaReader_New();
    vtkPlot3DMetaReader ret = (cPtr is null) ? null : new vtkPlot3DMetaReader(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkPlot3DMetaReader_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkPlot3DMetaReader SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkPlot3DMetaReader_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkPlot3DMetaReader ret = (cPtr is null) ? null : new vtkPlot3DMetaReader(cPtr, false);
    return ret;
  }

  public vtkPlot3DMetaReader NewInstance() const {
    void* cPtr = vtkd_im.vtkPlot3DMetaReader_NewInstance(cast(void*)swigCPtr);
    vtkPlot3DMetaReader ret = (cPtr is null) ? null : new vtkPlot3DMetaReader(cPtr, false);
    return ret;
  }

  alias vtkMultiBlockDataSetAlgorithm.vtkMultiBlockDataSetAlgorithm.NewInstance NewInstance;

  public void SetFileName(string _arg) {
    vtkd_im.vtkPlot3DMetaReader_SetFileName(cast(void*)swigCPtr, (_arg ? std.string.toStringz(_arg) : null));
  }

  public string GetFileName() {
    string ret = std.conv.to!string(vtkd_im.vtkPlot3DMetaReader_GetFileName(cast(void*)swigCPtr));
    return ret;
  }
}
