/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkPlotLine;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkPlotPoints;

class vtkPlotLine : vtkPlotPoints.vtkPlotPoints {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkPlotLine_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkPlotLine obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkPlotLine(cast(void*)swigCPtr);
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkPlotLine_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkPlotLine SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkPlotLine_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkPlotLine ret = (cPtr is null) ? null : new vtkPlotLine(cPtr, false);
    return ret;
  }

  public vtkPlotLine NewInstance() const {
    void* cPtr = vtkd_im.vtkPlotLine_NewInstance(cast(void*)swigCPtr);
    vtkPlotLine ret = (cPtr is null) ? null : new vtkPlotLine(cPtr, false);
    return ret;
  }

  alias vtkPlotPoints.vtkPlotPoints.NewInstance NewInstance;

  public static vtkPlotLine New() {
    void* cPtr = vtkd_im.vtkPlotLine_New();
    vtkPlotLine ret = (cPtr is null) ? null : new vtkPlotLine(cPtr, false);
    return ret;
  }

  public this() {
    this(vtkd_im.new_vtkPlotLine(), true);
  }
}
