/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkRectCharT;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkVectorChar4T;

class vtkRectCharT : vtkVectorChar4T.vtkVectorChar4T {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkRectCharT_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkRectCharT obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkRectCharT(cast(void*)swigCPtr);
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public this() {
    this(vtkd_im.new_vtkRectCharT__SWIG_0(), true);
  }

  public this(char x, char y, char width, char height) {
    this(vtkd_im.new_vtkRectCharT__SWIG_1(x, y, width, height), true);
  }

  public this(string init) {
    this(vtkd_im.new_vtkRectCharT__SWIG_2((init ? std.string.toStringz(init) : null)), true);
  }

  public void Set(char x, char y, char width, char height) {
    vtkd_im.vtkRectCharT_Set(cast(void*)swigCPtr, x, y, width, height);
  }

  public void SetX(char x) {
    vtkd_im.vtkRectCharT_SetX(cast(void*)swigCPtr, x);
  }

  public char GetX() const {
    auto ret = vtkd_im.vtkRectCharT_GetX(cast(void*)swigCPtr);
    return ret;
  }

  public void SetY(char y) {
    vtkd_im.vtkRectCharT_SetY(cast(void*)swigCPtr, y);
  }

  public char GetY() const {
    auto ret = vtkd_im.vtkRectCharT_GetY(cast(void*)swigCPtr);
    return ret;
  }

  public void SetWidth(char width) {
    vtkd_im.vtkRectCharT_SetWidth(cast(void*)swigCPtr, width);
  }

  public char GetWidth() const {
    auto ret = vtkd_im.vtkRectCharT_GetWidth(cast(void*)swigCPtr);
    return ret;
  }

  public void SetHeight(char height) {
    vtkd_im.vtkRectCharT_SetHeight(cast(void*)swigCPtr, height);
  }

  public char GetHeight() const {
    auto ret = vtkd_im.vtkRectCharT_GetHeight(cast(void*)swigCPtr);
    return ret;
  }

  public char X() const {
    auto ret = vtkd_im.vtkRectCharT_X(cast(void*)swigCPtr);
    return ret;
  }

  public char Y() const {
    auto ret = vtkd_im.vtkRectCharT_Y(cast(void*)swigCPtr);
    return ret;
  }

  public char Width() const {
    auto ret = vtkd_im.vtkRectCharT_Width(cast(void*)swigCPtr);
    return ret;
  }

  public char Height() const {
    auto ret = vtkd_im.vtkRectCharT_Height(cast(void*)swigCPtr);
    return ret;
  }
}
