/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkRISReader;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkTableAlgorithm;

class vtkRISReader : vtkTableAlgorithm.vtkTableAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkRISReader_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkRISReader obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkRISReader New() {
    void* cPtr = vtkd_im.vtkRISReader_New();
    vtkRISReader ret = (cPtr is null) ? null : new vtkRISReader(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkRISReader_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkRISReader SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkRISReader_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkRISReader ret = (cPtr is null) ? null : new vtkRISReader(cPtr, false);
    return ret;
  }

  public vtkRISReader NewInstance() const {
    void* cPtr = vtkd_im.vtkRISReader_NewInstance(cast(void*)swigCPtr);
    vtkRISReader ret = (cPtr is null) ? null : new vtkRISReader(cPtr, false);
    return ret;
  }

  alias vtkTableAlgorithm.vtkTableAlgorithm.NewInstance NewInstance;

  public string GetFileName() {
    string ret = std.conv.to!string(vtkd_im.vtkRISReader_GetFileName(cast(void*)swigCPtr));
    return ret;
  }

  public void SetFileName(string _arg) {
    vtkd_im.vtkRISReader_SetFileName(cast(void*)swigCPtr, (_arg ? std.string.toStringz(_arg) : null));
  }

  public string GetDelimiter() {
    string ret = std.conv.to!string(vtkd_im.vtkRISReader_GetDelimiter(cast(void*)swigCPtr));
    return ret;
  }

  public void SetDelimiter(string _arg) {
    vtkd_im.vtkRISReader_SetDelimiter(cast(void*)swigCPtr, (_arg ? std.string.toStringz(_arg) : null));
  }

  public int GetMaxRecords() {
    auto ret = vtkd_im.vtkRISReader_GetMaxRecords(cast(void*)swigCPtr);
    return ret;
  }

  public void SetMaxRecords(int _arg) {
    vtkd_im.vtkRISReader_SetMaxRecords(cast(void*)swigCPtr, _arg);
  }
}
