/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkSQLiteToTableReader;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDatabaseToTableReader;

class vtkSQLiteToTableReader : vtkDatabaseToTableReader.vtkDatabaseToTableReader {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkSQLiteToTableReader_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkSQLiteToTableReader obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkSQLiteToTableReader New() {
    void* cPtr = vtkd_im.vtkSQLiteToTableReader_New();
    vtkSQLiteToTableReader ret = (cPtr is null) ? null : new vtkSQLiteToTableReader(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkSQLiteToTableReader_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkSQLiteToTableReader SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkSQLiteToTableReader_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkSQLiteToTableReader ret = (cPtr is null) ? null : new vtkSQLiteToTableReader(cPtr, false);
    return ret;
  }

  public vtkSQLiteToTableReader NewInstance() const {
    void* cPtr = vtkd_im.vtkSQLiteToTableReader_NewInstance(cast(void*)swigCPtr);
    vtkSQLiteToTableReader ret = (cPtr is null) ? null : new vtkSQLiteToTableReader(cPtr, false);
    return ret;
  }

  alias vtkDatabaseToTableReader.vtkDatabaseToTableReader.NewInstance NewInstance;
}
