/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkStructuredGridWriter;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkStructuredGrid;
static import vtkDataWriter;

class vtkStructuredGridWriter : vtkDataWriter.vtkDataWriter {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkStructuredGridWriter_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkStructuredGridWriter obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkStructuredGridWriter New() {
    void* cPtr = vtkd_im.vtkStructuredGridWriter_New();
    vtkStructuredGridWriter ret = (cPtr is null) ? null : new vtkStructuredGridWriter(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkStructuredGridWriter_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkStructuredGridWriter SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkStructuredGridWriter_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkStructuredGridWriter ret = (cPtr is null) ? null : new vtkStructuredGridWriter(cPtr, false);
    return ret;
  }

  public vtkStructuredGridWriter NewInstance() const {
    void* cPtr = vtkd_im.vtkStructuredGridWriter_NewInstance(cast(void*)swigCPtr);
    vtkStructuredGridWriter ret = (cPtr is null) ? null : new vtkStructuredGridWriter(cPtr, false);
    return ret;
  }

  alias vtkDataWriter.vtkDataWriter.NewInstance NewInstance;

  public vtkStructuredGrid.vtkStructuredGrid GetInput() {
    void* cPtr = vtkd_im.vtkStructuredGridWriter_GetInput__SWIG_0(cast(void*)swigCPtr);
    vtkStructuredGrid.vtkStructuredGrid ret = (cPtr is null) ? null : new vtkStructuredGrid.vtkStructuredGrid(cPtr, false);
    return ret;
  }

  public vtkStructuredGrid.vtkStructuredGrid GetInput(int port) {
    void* cPtr = vtkd_im.vtkStructuredGridWriter_GetInput__SWIG_1(cast(void*)swigCPtr, port);
    vtkStructuredGrid.vtkStructuredGrid ret = (cPtr is null) ? null : new vtkStructuredGrid.vtkStructuredGrid(cPtr, false);
    return ret;
  }
}
