/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkSpiderPlotActor;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDataObject;
static import vtkAlgorithmOutput;
static import vtkTextProperty;
static import SWIGTYPE_p_double;
static import vtkLegendBoxActor;
static import vtkActor2D;

class vtkSpiderPlotActor : vtkActor2D.vtkActor2D {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkSpiderPlotActor_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkSpiderPlotActor obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkSpiderPlotActor_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkSpiderPlotActor SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkSpiderPlotActor_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkSpiderPlotActor ret = (cPtr is null) ? null : new vtkSpiderPlotActor(cPtr, false);
    return ret;
  }

  public vtkSpiderPlotActor NewInstance() const {
    void* cPtr = vtkd_im.vtkSpiderPlotActor_NewInstance(cast(void*)swigCPtr);
    vtkSpiderPlotActor ret = (cPtr is null) ? null : new vtkSpiderPlotActor(cPtr, false);
    return ret;
  }

  alias vtkActor2D.vtkActor2D.NewInstance NewInstance;

  public static vtkSpiderPlotActor New() {
    void* cPtr = vtkd_im.vtkSpiderPlotActor_New();
    vtkSpiderPlotActor ret = (cPtr is null) ? null : new vtkSpiderPlotActor(cPtr, false);
    return ret;
  }

  public void SetInputData(vtkDataObject.vtkDataObject arg0) {
    vtkd_im.vtkSpiderPlotActor_SetInputData(cast(void*)swigCPtr, vtkDataObject.vtkDataObject.swigGetCPtr(arg0));
  }

  public void SetInputConnection(vtkAlgorithmOutput.vtkAlgorithmOutput arg0) {
    vtkd_im.vtkSpiderPlotActor_SetInputConnection(cast(void*)swigCPtr, vtkAlgorithmOutput.vtkAlgorithmOutput.swigGetCPtr(arg0));
  }

  public vtkDataObject.vtkDataObject GetInput() {
    void* cPtr = vtkd_im.vtkSpiderPlotActor_GetInput(cast(void*)swigCPtr);
    vtkDataObject.vtkDataObject ret = (cPtr is null) ? null : new vtkDataObject.vtkDataObject(cPtr, false);
    return ret;
  }

  public void SetIndependentVariables(int _arg) {
    vtkd_im.vtkSpiderPlotActor_SetIndependentVariables(cast(void*)swigCPtr, _arg);
  }

  public int GetIndependentVariablesMinValue() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetIndependentVariablesMinValue(cast(void*)swigCPtr);
    return ret;
  }

  public int GetIndependentVariablesMaxValue() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetIndependentVariablesMaxValue(cast(void*)swigCPtr);
    return ret;
  }

  public int GetIndependentVariables() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetIndependentVariables(cast(void*)swigCPtr);
    return ret;
  }

  public void SetIndependentVariablesToColumns() {
    vtkd_im.vtkSpiderPlotActor_SetIndependentVariablesToColumns(cast(void*)swigCPtr);
  }

  public void SetIndependentVariablesToRows() {
    vtkd_im.vtkSpiderPlotActor_SetIndependentVariablesToRows(cast(void*)swigCPtr);
  }

  public void SetTitleVisibility(int _arg) {
    vtkd_im.vtkSpiderPlotActor_SetTitleVisibility(cast(void*)swigCPtr, _arg);
  }

  public int GetTitleVisibility() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetTitleVisibility(cast(void*)swigCPtr);
    return ret;
  }

  public void TitleVisibilityOn() {
    vtkd_im.vtkSpiderPlotActor_TitleVisibilityOn(cast(void*)swigCPtr);
  }

  public void TitleVisibilityOff() {
    vtkd_im.vtkSpiderPlotActor_TitleVisibilityOff(cast(void*)swigCPtr);
  }

  public void SetTitle(string _arg) {
    vtkd_im.vtkSpiderPlotActor_SetTitle(cast(void*)swigCPtr, (_arg ? std.string.toStringz(_arg) : null));
  }

  public string GetTitle() {
    string ret = std.conv.to!string(vtkd_im.vtkSpiderPlotActor_GetTitle(cast(void*)swigCPtr));
    return ret;
  }

  public void SetTitleTextProperty(vtkTextProperty.vtkTextProperty p) {
    vtkd_im.vtkSpiderPlotActor_SetTitleTextProperty(cast(void*)swigCPtr, vtkTextProperty.vtkTextProperty.swigGetCPtr(p));
  }

  public vtkTextProperty.vtkTextProperty GetTitleTextProperty() {
    void* cPtr = vtkd_im.vtkSpiderPlotActor_GetTitleTextProperty(cast(void*)swigCPtr);
    vtkTextProperty.vtkTextProperty ret = (cPtr is null) ? null : new vtkTextProperty.vtkTextProperty(cPtr, false);
    return ret;
  }

  public void SetLabelVisibility(int _arg) {
    vtkd_im.vtkSpiderPlotActor_SetLabelVisibility(cast(void*)swigCPtr, _arg);
  }

  public int GetLabelVisibility() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetLabelVisibility(cast(void*)swigCPtr);
    return ret;
  }

  public void LabelVisibilityOn() {
    vtkd_im.vtkSpiderPlotActor_LabelVisibilityOn(cast(void*)swigCPtr);
  }

  public void LabelVisibilityOff() {
    vtkd_im.vtkSpiderPlotActor_LabelVisibilityOff(cast(void*)swigCPtr);
  }

  public void SetLabelTextProperty(vtkTextProperty.vtkTextProperty p) {
    vtkd_im.vtkSpiderPlotActor_SetLabelTextProperty(cast(void*)swigCPtr, vtkTextProperty.vtkTextProperty.swigGetCPtr(p));
  }

  public vtkTextProperty.vtkTextProperty GetLabelTextProperty() {
    void* cPtr = vtkd_im.vtkSpiderPlotActor_GetLabelTextProperty(cast(void*)swigCPtr);
    vtkTextProperty.vtkTextProperty ret = (cPtr is null) ? null : new vtkTextProperty.vtkTextProperty(cPtr, false);
    return ret;
  }

  public void SetNumberOfRings(int _arg) {
    vtkd_im.vtkSpiderPlotActor_SetNumberOfRings(cast(void*)swigCPtr, _arg);
  }

  public int GetNumberOfRingsMinValue() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetNumberOfRingsMinValue(cast(void*)swigCPtr);
    return ret;
  }

  public int GetNumberOfRingsMaxValue() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetNumberOfRingsMaxValue(cast(void*)swigCPtr);
    return ret;
  }

  public int GetNumberOfRings() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetNumberOfRings(cast(void*)swigCPtr);
    return ret;
  }

  public void SetAxisLabel(int i, string arg1) {
    vtkd_im.vtkSpiderPlotActor_SetAxisLabel(cast(void*)swigCPtr, i, (arg1 ? std.string.toStringz(arg1) : null));
  }

  public string GetAxisLabel(int i) {
    string ret = std.conv.to!string(vtkd_im.vtkSpiderPlotActor_GetAxisLabel(cast(void*)swigCPtr, i));
    return ret;
  }

  public void SetAxisRange(int i, double min, double max) {
    vtkd_im.vtkSpiderPlotActor_SetAxisRange__SWIG_0(cast(void*)swigCPtr, i, min, max);
  }

  public void SetAxisRange(int i, SWIGTYPE_p_double.SWIGTYPE_p_double range) {
    vtkd_im.vtkSpiderPlotActor_SetAxisRange__SWIG_1(cast(void*)swigCPtr, i, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(range));
  }

  public void GetAxisRange(int i, SWIGTYPE_p_double.SWIGTYPE_p_double range) {
    vtkd_im.vtkSpiderPlotActor_GetAxisRange(cast(void*)swigCPtr, i, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(range));
  }

  public void SetPlotColor(int i, double r, double g, double b) {
    vtkd_im.vtkSpiderPlotActor_SetPlotColor__SWIG_0(cast(void*)swigCPtr, i, r, g, b);
  }

  public void SetPlotColor(int i, SWIGTYPE_p_double.SWIGTYPE_p_double color) {
    vtkd_im.vtkSpiderPlotActor_SetPlotColor__SWIG_1(cast(void*)swigCPtr, i, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(color));
  }

  public double* GetPlotColor(int i) {
    auto ret = cast(double*)vtkd_im.vtkSpiderPlotActor_GetPlotColor(cast(void*)swigCPtr, i);
    return ret;
  }

  public void SetLegendVisibility(int _arg) {
    vtkd_im.vtkSpiderPlotActor_SetLegendVisibility(cast(void*)swigCPtr, _arg);
  }

  public int GetLegendVisibility() {
    auto ret = vtkd_im.vtkSpiderPlotActor_GetLegendVisibility(cast(void*)swigCPtr);
    return ret;
  }

  public void LegendVisibilityOn() {
    vtkd_im.vtkSpiderPlotActor_LegendVisibilityOn(cast(void*)swigCPtr);
  }

  public void LegendVisibilityOff() {
    vtkd_im.vtkSpiderPlotActor_LegendVisibilityOff(cast(void*)swigCPtr);
  }

  public vtkLegendBoxActor.vtkLegendBoxActor GetLegendActor() {
    void* cPtr = vtkd_im.vtkSpiderPlotActor_GetLegendActor(cast(void*)swigCPtr);
    vtkLegendBoxActor.vtkLegendBoxActor ret = (cPtr is null) ? null : new vtkLegendBoxActor.vtkLegendBoxActor(cPtr, false);
    return ret;
  }
}
