/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkSquarifyLayoutStrategy;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkTreeMapLayoutStrategy;

class vtkSquarifyLayoutStrategy : vtkTreeMapLayoutStrategy.vtkTreeMapLayoutStrategy {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkSquarifyLayoutStrategy_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkSquarifyLayoutStrategy obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkSquarifyLayoutStrategy New() {
    void* cPtr = vtkd_im.vtkSquarifyLayoutStrategy_New();
    vtkSquarifyLayoutStrategy ret = (cPtr is null) ? null : new vtkSquarifyLayoutStrategy(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkSquarifyLayoutStrategy_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkSquarifyLayoutStrategy SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkSquarifyLayoutStrategy_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkSquarifyLayoutStrategy ret = (cPtr is null) ? null : new vtkSquarifyLayoutStrategy(cPtr, false);
    return ret;
  }

  public vtkSquarifyLayoutStrategy NewInstance() const {
    void* cPtr = vtkd_im.vtkSquarifyLayoutStrategy_NewInstance(cast(void*)swigCPtr);
    vtkSquarifyLayoutStrategy ret = (cPtr is null) ? null : new vtkSquarifyLayoutStrategy(cPtr, false);
    return ret;
  }

  alias vtkTreeMapLayoutStrategy.vtkTreeMapLayoutStrategy.NewInstance NewInstance;
}
