/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkTransposeMatrix;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkArrayDataAlgorithm;

class vtkTransposeMatrix : vtkArrayDataAlgorithm.vtkArrayDataAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkTransposeMatrix_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkTransposeMatrix obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkTransposeMatrix New() {
    void* cPtr = vtkd_im.vtkTransposeMatrix_New();
    vtkTransposeMatrix ret = (cPtr is null) ? null : new vtkTransposeMatrix(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkTransposeMatrix_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkTransposeMatrix SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkTransposeMatrix_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkTransposeMatrix ret = (cPtr is null) ? null : new vtkTransposeMatrix(cPtr, false);
    return ret;
  }

  public vtkTransposeMatrix NewInstance() const {
    void* cPtr = vtkd_im.vtkTransposeMatrix_NewInstance(cast(void*)swigCPtr);
    vtkTransposeMatrix ret = (cPtr is null) ? null : new vtkTransposeMatrix(cPtr, false);
    return ret;
  }

  alias vtkArrayDataAlgorithm.vtkArrayDataAlgorithm.NewInstance NewInstance;
}
