/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkTStripsPainter;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkPrimitivePainter;

class vtkTStripsPainter : vtkPrimitivePainter.vtkPrimitivePainter {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkTStripsPainter_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkTStripsPainter obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkTStripsPainter New() {
    void* cPtr = vtkd_im.vtkTStripsPainter_New();
    vtkTStripsPainter ret = (cPtr is null) ? null : new vtkTStripsPainter(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkTStripsPainter_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkTStripsPainter SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkTStripsPainter_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkTStripsPainter ret = (cPtr is null) ? null : new vtkTStripsPainter(cPtr, false);
    return ret;
  }

  public vtkTStripsPainter NewInstance() const {
    void* cPtr = vtkd_im.vtkTStripsPainter_NewInstance(cast(void*)swigCPtr);
    vtkTStripsPainter ret = (cPtr is null) ? null : new vtkTStripsPainter(cPtr, false);
    return ret;
  }

  alias vtkPrimitivePainter.vtkPrimitivePainter.NewInstance NewInstance;
}
