/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkTableAlgorithm;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkTable;
static import vtkDataObject;
static import vtkAlgorithm;

class vtkTableAlgorithm : vtkAlgorithm.vtkAlgorithm {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkTableAlgorithm_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkTableAlgorithm obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkTableAlgorithm New() {
    void* cPtr = vtkd_im.vtkTableAlgorithm_New();
    vtkTableAlgorithm ret = (cPtr is null) ? null : new vtkTableAlgorithm(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkTableAlgorithm_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkTableAlgorithm SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkTableAlgorithm_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkTableAlgorithm ret = (cPtr is null) ? null : new vtkTableAlgorithm(cPtr, false);
    return ret;
  }

  public vtkTableAlgorithm NewInstance() const {
    void* cPtr = vtkd_im.vtkTableAlgorithm_NewInstance(cast(void*)swigCPtr);
    vtkTableAlgorithm ret = (cPtr is null) ? null : new vtkTableAlgorithm(cPtr, false);
    return ret;
  }

  alias vtkAlgorithm.vtkAlgorithm.NewInstance NewInstance;

  public vtkTable.vtkTable GetOutput() {
    void* cPtr = vtkd_im.vtkTableAlgorithm_GetOutput__SWIG_0(cast(void*)swigCPtr);
    vtkTable.vtkTable ret = (cPtr is null) ? null : new vtkTable.vtkTable(cPtr, false);
    return ret;
  }

  public vtkTable.vtkTable GetOutput(int index) {
    void* cPtr = vtkd_im.vtkTableAlgorithm_GetOutput__SWIG_1(cast(void*)swigCPtr, index);
    vtkTable.vtkTable ret = (cPtr is null) ? null : new vtkTable.vtkTable(cPtr, false);
    return ret;
  }

  public void SetInputData(vtkDataObject.vtkDataObject obj) {
    vtkd_im.vtkTableAlgorithm_SetInputData__SWIG_0(cast(void*)swigCPtr, vtkDataObject.vtkDataObject.swigGetCPtr(obj));
  }

  public void SetInputData(int index, vtkDataObject.vtkDataObject obj) {
    vtkd_im.vtkTableAlgorithm_SetInputData__SWIG_1(cast(void*)swigCPtr, index, vtkDataObject.vtkDataObject.swigGetCPtr(obj));
  }
}
