/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkTensorProbeRepresentation;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import SWIGTYPE_p_double;
static import vtkPolyData;
static import SWIGTYPE_p_int;
static import vtkWidgetRepresentation;

class vtkTensorProbeRepresentation : vtkWidgetRepresentation.vtkWidgetRepresentation {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkTensorProbeRepresentation_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkTensorProbeRepresentation obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkTensorProbeRepresentation_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkTensorProbeRepresentation SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkTensorProbeRepresentation_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkTensorProbeRepresentation ret = (cPtr is null) ? null : new vtkTensorProbeRepresentation(cPtr, false);
    return ret;
  }

  public vtkTensorProbeRepresentation NewInstance() const {
    void* cPtr = vtkd_im.vtkTensorProbeRepresentation_NewInstance(cast(void*)swigCPtr);
    vtkTensorProbeRepresentation ret = (cPtr is null) ? null : new vtkTensorProbeRepresentation(cPtr, false);
    return ret;
  }

  alias vtkWidgetRepresentation.vtkWidgetRepresentation.NewInstance NewInstance;

  public void SetProbePosition(double _arg1, double _arg2, double _arg3) {
    vtkd_im.vtkTensorProbeRepresentation_SetProbePosition__SWIG_0(cast(void*)swigCPtr, _arg1, _arg2, _arg3);
  }

  public void SetProbePosition(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkTensorProbeRepresentation_SetProbePosition__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public double* GetProbePosition() {
    auto ret = cast(double*)vtkd_im.vtkTensorProbeRepresentation_GetProbePosition__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetProbePosition(double* _arg1, double* _arg2, double* _arg3) {
    vtkd_im.vtkTensorProbeRepresentation_GetProbePosition__SWIG_1(cast(void*)swigCPtr, cast(void*)_arg1, cast(void*)_arg2, cast(void*)_arg3);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetProbePosition(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkTensorProbeRepresentation_GetProbePosition__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public void SetProbeCellId(long _arg) {
    vtkd_im.vtkTensorProbeRepresentation_SetProbeCellId(cast(void*)swigCPtr, _arg);
  }

  public long GetProbeCellId() {
    auto ret = vtkd_im.vtkTensorProbeRepresentation_GetProbeCellId(cast(void*)swigCPtr);
    return ret;
  }

  public void SetTrajectory(vtkPolyData.vtkPolyData arg0) {
    vtkd_im.vtkTensorProbeRepresentation_SetTrajectory(cast(void*)swigCPtr, vtkPolyData.vtkPolyData.swigGetCPtr(arg0));
  }

  public void Initialize() {
    vtkd_im.vtkTensorProbeRepresentation_Initialize(cast(void*)swigCPtr);
  }

  public int SelectProbe(SWIGTYPE_p_int.SWIGTYPE_p_int pos) {
    auto ret = vtkd_im.vtkTensorProbeRepresentation_SelectProbe(cast(void*)swigCPtr, SWIGTYPE_p_int.SWIGTYPE_p_int.swigGetCPtr(pos));
    return ret;
  }

  public int Move(SWIGTYPE_p_double.SWIGTYPE_p_double motionVector) {
    auto ret = vtkd_im.vtkTensorProbeRepresentation_Move(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(motionVector));
    return ret;
  }
}
