/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkTypeFloat64Array;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import vtkDoubleArray;

class vtkTypeFloat64Array : vtkDoubleArray.vtkDoubleArray {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkTypeFloat64Array_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkTypeFloat64Array obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkTypeFloat64Array New() {
    void* cPtr = vtkd_im.vtkTypeFloat64Array_New();
    vtkTypeFloat64Array ret = (cPtr is null) ? null : new vtkTypeFloat64Array(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkTypeFloat64Array_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkTypeFloat64Array SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkTypeFloat64Array_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkTypeFloat64Array ret = (cPtr is null) ? null : new vtkTypeFloat64Array(cPtr, false);
    return ret;
  }

  public vtkTypeFloat64Array NewInstance() const {
    void* cPtr = vtkd_im.vtkTypeFloat64Array_NewInstance(cast(void*)swigCPtr);
    vtkTypeFloat64Array ret = (cPtr is null) ? null : new vtkTypeFloat64Array(cPtr, false);
    return ret;
  }

  alias vtkDoubleArray.vtkDoubleArray.NewInstance NewInstance;
}
