/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkUnsignedShortColor3T;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkUnsignedShortTuple3TN;

class vtkUnsignedShortColor3T : vtkUnsignedShortTuple3TN.vtkUnsignedShortTuple3TN {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkUnsignedShortColor3T_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkUnsignedShortColor3T obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkUnsignedShortColor3T(cast(void*)swigCPtr);
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public this() {
    this(vtkd_im.new_vtkUnsignedShortColor3T__SWIG_0(), true);
  }

  public this(ushort scalar) {
    this(vtkd_im.new_vtkUnsignedShortColor3T__SWIG_1(scalar), true);
  }

  public this(ushort* init) {
    this(vtkd_im.new_vtkUnsignedShortColor3T__SWIG_2(cast(void*)init), true);
  }

  public this(ushort red, ushort green, ushort blue) {
    this(vtkd_im.new_vtkUnsignedShortColor3T__SWIG_3(red, green, blue), true);
  }

  public void Set(ushort red, ushort green, ushort blue) {
    vtkd_im.vtkUnsignedShortColor3T_Set(cast(void*)swigCPtr, red, green, blue);
  }

  public void SetRed(ushort red) {
    vtkd_im.vtkUnsignedShortColor3T_SetRed(cast(void*)swigCPtr, red);
  }

  public ushort GetRed() const {
    auto ret = vtkd_im.vtkUnsignedShortColor3T_GetRed(cast(void*)swigCPtr);
    return ret;
  }

  public void SetGreen(ushort green) {
    vtkd_im.vtkUnsignedShortColor3T_SetGreen(cast(void*)swigCPtr, green);
  }

  public ushort GetGreen() const {
    auto ret = vtkd_im.vtkUnsignedShortColor3T_GetGreen(cast(void*)swigCPtr);
    return ret;
  }

  public void SetBlue(ushort blue) {
    vtkd_im.vtkUnsignedShortColor3T_SetBlue(cast(void*)swigCPtr, blue);
  }

  public ushort GetBlue() const {
    auto ret = vtkd_im.vtkUnsignedShortColor3T_GetBlue(cast(void*)swigCPtr);
    return ret;
  }

  public ushort Red() const {
    auto ret = vtkd_im.vtkUnsignedShortColor3T_Red(cast(void*)swigCPtr);
    return ret;
  }

  public ushort Green() const {
    auto ret = vtkd_im.vtkUnsignedShortColor3T_Green(cast(void*)swigCPtr);
    return ret;
  }

  public ushort Blue() const {
    auto ret = vtkd_im.vtkUnsignedShortColor3T_Blue(cast(void*)swigCPtr);
    return ret;
  }
}
