/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkUnsignedLongRectT;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkVectorULong4T;

class vtkUnsignedLongRectT : vtkVectorULong4T.vtkVectorULong4T {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkUnsignedLongRectT_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkUnsignedLongRectT obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkUnsignedLongRectT(cast(void*)swigCPtr);
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public this() {
    this(vtkd_im.new_vtkUnsignedLongRectT__SWIG_0(), true);
  }

  public this(core.stdc.config.c_ulong x, core.stdc.config.c_ulong y, core.stdc.config.c_ulong width, core.stdc.config.c_ulong height) {
    this(vtkd_im.new_vtkUnsignedLongRectT__SWIG_1(x, y, width, height), true);
  }

  public this(core.stdc.config.c_ulong* init) {
    this(vtkd_im.new_vtkUnsignedLongRectT__SWIG_2(cast(void*)init), true);
  }

  public void Set(core.stdc.config.c_ulong x, core.stdc.config.c_ulong y, core.stdc.config.c_ulong width, core.stdc.config.c_ulong height) {
    vtkd_im.vtkUnsignedLongRectT_Set(cast(void*)swigCPtr, x, y, width, height);
  }

  public void SetX(core.stdc.config.c_ulong x) {
    vtkd_im.vtkUnsignedLongRectT_SetX(cast(void*)swigCPtr, x);
  }

  public core.stdc.config.c_ulong GetX() const {
    auto ret = vtkd_im.vtkUnsignedLongRectT_GetX(cast(void*)swigCPtr);
    return ret;
  }

  public void SetY(core.stdc.config.c_ulong y) {
    vtkd_im.vtkUnsignedLongRectT_SetY(cast(void*)swigCPtr, y);
  }

  public core.stdc.config.c_ulong GetY() const {
    auto ret = vtkd_im.vtkUnsignedLongRectT_GetY(cast(void*)swigCPtr);
    return ret;
  }

  public void SetWidth(core.stdc.config.c_ulong width) {
    vtkd_im.vtkUnsignedLongRectT_SetWidth(cast(void*)swigCPtr, width);
  }

  public core.stdc.config.c_ulong GetWidth() const {
    auto ret = vtkd_im.vtkUnsignedLongRectT_GetWidth(cast(void*)swigCPtr);
    return ret;
  }

  public void SetHeight(core.stdc.config.c_ulong height) {
    vtkd_im.vtkUnsignedLongRectT_SetHeight(cast(void*)swigCPtr, height);
  }

  public core.stdc.config.c_ulong GetHeight() const {
    auto ret = vtkd_im.vtkUnsignedLongRectT_GetHeight(cast(void*)swigCPtr);
    return ret;
  }

  public core.stdc.config.c_ulong X() const {
    auto ret = vtkd_im.vtkUnsignedLongRectT_X(cast(void*)swigCPtr);
    return ret;
  }

  public core.stdc.config.c_ulong Y() const {
    auto ret = vtkd_im.vtkUnsignedLongRectT_Y(cast(void*)swigCPtr);
    return ret;
  }

  public core.stdc.config.c_ulong Width() const {
    auto ret = vtkd_im.vtkUnsignedLongRectT_Width(cast(void*)swigCPtr);
    return ret;
  }

  public core.stdc.config.c_ulong Height() const {
    auto ret = vtkd_im.vtkUnsignedLongRectT_Height(cast(void*)swigCPtr);
    return ret;
  }
}
