/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkUnsignedShortVector3TN;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkUnsignedShortTuple3TN;

class vtkUnsignedShortVector3TN : vtkUnsignedShortTuple3TN.vtkUnsignedShortTuple3TN {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkUnsignedShortVector3TN_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkUnsignedShortVector3TN obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  ~this() {
    dispose();
  }

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          vtkd_im.delete_vtkUnsignedShortVector3TN(cast(void*)swigCPtr);
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public this() {
    this(vtkd_im.new_vtkUnsignedShortVector3TN__SWIG_0(), true);
  }

  public this(ushort scalar) {
    this(vtkd_im.new_vtkUnsignedShortVector3TN__SWIG_1(scalar), true);
  }

  public this(ushort* init) {
    this(vtkd_im.new_vtkUnsignedShortVector3TN__SWIG_2(cast(void*)init), true);
  }

  public ushort SquaredNorm() const {
    auto ret = vtkd_im.vtkUnsignedShortVector3TN_SquaredNorm(cast(void*)swigCPtr);
    return ret;
  }

  public double Norm() const {
    auto ret = vtkd_im.vtkUnsignedShortVector3TN_Norm(cast(void*)swigCPtr);
    return ret;
  }

  public double Normalize() {
    auto ret = vtkd_im.vtkUnsignedShortVector3TN_Normalize(cast(void*)swigCPtr);
    return ret;
  }

  public vtkUnsignedShortVector3TN Normalized() const {
    vtkUnsignedShortVector3TN ret = new vtkUnsignedShortVector3TN(vtkd_im.vtkUnsignedShortVector3TN_Normalized(cast(void*)swigCPtr), true);
    return ret;
  }

  public ushort Dot(vtkUnsignedShortVector3TN other) const {
    auto ret = vtkd_im.vtkUnsignedShortVector3TN_Dot(cast(void*)swigCPtr, vtkUnsignedShortVector3TN.swigGetCPtr(other));
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
    return ret;
  }
}
