/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

module vtkViewTheme;

static import vtkd_im;
static import core.stdc.config;

static import std.conv;
static import std.string;

static import std.conv;
static import std.string;
static import vtkObjectBase;
static import SWIGTYPE_p_double;
static import vtkScalarsToColors;
static import vtkTextProperty;
static import vtkObject;

class vtkViewTheme : vtkObject.vtkObject {
  private void* swigCPtr;

  public this(void* cObject, bool ownCObject) {
    super(vtkd_im.vtkViewTheme_Upcast(cObject), ownCObject);
    swigCPtr = cObject;
  }

  public static void* swigGetCPtr(vtkViewTheme obj) {
    return (obj is null) ? null : obj.swigCPtr;
  }

  mixin vtkd_im.SwigOperatorDefinitions;

  public override void dispose() {
    synchronized(this) {
      if (swigCPtr !is null) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new object.Exception("C++ destructor does not have public access");
        }
        swigCPtr = null;
        super.dispose();
      }
    }
  }

  public static vtkViewTheme New() {
    void* cPtr = vtkd_im.vtkViewTheme_New();
    vtkViewTheme ret = (cPtr is null) ? null : new vtkViewTheme(cPtr, false);
    return ret;
  }

  public static int IsTypeOf(string type) {
    auto ret = vtkd_im.vtkViewTheme_IsTypeOf((type ? std.string.toStringz(type) : null));
    return ret;
  }

  public static vtkViewTheme SafeDownCast(vtkObjectBase.vtkObjectBase o) {
    void* cPtr = vtkd_im.vtkViewTheme_SafeDownCast(vtkObjectBase.vtkObjectBase.swigGetCPtr(o));
    vtkViewTheme ret = (cPtr is null) ? null : new vtkViewTheme(cPtr, false);
    return ret;
  }

  public vtkViewTheme NewInstance() const {
    void* cPtr = vtkd_im.vtkViewTheme_NewInstance(cast(void*)swigCPtr);
    vtkViewTheme ret = (cPtr is null) ? null : new vtkViewTheme(cPtr, false);
    return ret;
  }

  alias vtkObject.vtkObject.NewInstance NewInstance;

  public void SetPointSize(double _arg) {
    vtkd_im.vtkViewTheme_SetPointSize(cast(void*)swigCPtr, _arg);
  }

  public double GetPointSize() {
    auto ret = vtkd_im.vtkViewTheme_GetPointSize(cast(void*)swigCPtr);
    return ret;
  }

  public void SetLineWidth(double _arg) {
    vtkd_im.vtkViewTheme_SetLineWidth(cast(void*)swigCPtr, _arg);
  }

  public double GetLineWidth() {
    auto ret = vtkd_im.vtkViewTheme_GetLineWidth(cast(void*)swigCPtr);
    return ret;
  }

  public void SetPointColor(double _arg1, double _arg2, double _arg3) {
    vtkd_im.vtkViewTheme_SetPointColor__SWIG_0(cast(void*)swigCPtr, _arg1, _arg2, _arg3);
  }

  public void SetPointColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_SetPointColor__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public double* GetPointColor() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetPointColor__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetPointColor(double* _arg1, double* _arg2, double* _arg3) {
    vtkd_im.vtkViewTheme_GetPointColor__SWIG_1(cast(void*)swigCPtr, cast(void*)_arg1, cast(void*)_arg2, cast(void*)_arg3);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetPointColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_GetPointColor__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public void SetPointOpacity(double _arg) {
    vtkd_im.vtkViewTheme_SetPointOpacity(cast(void*)swigCPtr, _arg);
  }

  public double GetPointOpacity() {
    auto ret = vtkd_im.vtkViewTheme_GetPointOpacity(cast(void*)swigCPtr);
    return ret;
  }

  public void SetPointHueRange(double mn, double mx) {
    vtkd_im.vtkViewTheme_SetPointHueRange__SWIG_0(cast(void*)swigCPtr, mn, mx);
  }

  public void SetPointHueRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_SetPointHueRange__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public double* GetPointHueRange() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetPointHueRange__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetPointHueRange(double* mn, double* mx) {
    vtkd_im.vtkViewTheme_GetPointHueRange__SWIG_1(cast(void*)swigCPtr, cast(void*)mn, cast(void*)mx);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetPointHueRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_GetPointHueRange__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public void SetPointSaturationRange(double mn, double mx) {
    vtkd_im.vtkViewTheme_SetPointSaturationRange__SWIG_0(cast(void*)swigCPtr, mn, mx);
  }

  public void SetPointSaturationRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_SetPointSaturationRange__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public double* GetPointSaturationRange() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetPointSaturationRange__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetPointSaturationRange(double* mn, double* mx) {
    vtkd_im.vtkViewTheme_GetPointSaturationRange__SWIG_1(cast(void*)swigCPtr, cast(void*)mn, cast(void*)mx);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetPointSaturationRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_GetPointSaturationRange__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public void SetPointValueRange(double mn, double mx) {
    vtkd_im.vtkViewTheme_SetPointValueRange__SWIG_0(cast(void*)swigCPtr, mn, mx);
  }

  public void SetPointValueRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_SetPointValueRange__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public double* GetPointValueRange() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetPointValueRange__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetPointValueRange(double* mn, double* mx) {
    vtkd_im.vtkViewTheme_GetPointValueRange__SWIG_1(cast(void*)swigCPtr, cast(void*)mn, cast(void*)mx);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetPointValueRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_GetPointValueRange__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public void SetPointAlphaRange(double mn, double mx) {
    vtkd_im.vtkViewTheme_SetPointAlphaRange__SWIG_0(cast(void*)swigCPtr, mn, mx);
  }

  public void SetPointAlphaRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_SetPointAlphaRange__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public double* GetPointAlphaRange() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetPointAlphaRange__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetPointAlphaRange(double* mn, double* mx) {
    vtkd_im.vtkViewTheme_GetPointAlphaRange__SWIG_1(cast(void*)swigCPtr, cast(void*)mn, cast(void*)mx);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetPointAlphaRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_GetPointAlphaRange__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public vtkScalarsToColors.vtkScalarsToColors GetPointLookupTable() {
    void* cPtr = vtkd_im.vtkViewTheme_GetPointLookupTable(cast(void*)swigCPtr);
    vtkScalarsToColors.vtkScalarsToColors ret = (cPtr is null) ? null : new vtkScalarsToColors.vtkScalarsToColors(cPtr, false);
    return ret;
  }

  public void SetPointLookupTable(vtkScalarsToColors.vtkScalarsToColors lut) {
    vtkd_im.vtkViewTheme_SetPointLookupTable(cast(void*)swigCPtr, vtkScalarsToColors.vtkScalarsToColors.swigGetCPtr(lut));
  }

  public void SetScalePointLookupTable(bool _arg) {
    vtkd_im.vtkViewTheme_SetScalePointLookupTable(cast(void*)swigCPtr, _arg);
  }

  public bool GetScalePointLookupTable() {
    bool ret = vtkd_im.vtkViewTheme_GetScalePointLookupTable(cast(void*)swigCPtr) ? true : false;
    return ret;
  }

  public void ScalePointLookupTableOn() {
    vtkd_im.vtkViewTheme_ScalePointLookupTableOn(cast(void*)swigCPtr);
  }

  public void ScalePointLookupTableOff() {
    vtkd_im.vtkViewTheme_ScalePointLookupTableOff(cast(void*)swigCPtr);
  }

  public void SetCellColor(double _arg1, double _arg2, double _arg3) {
    vtkd_im.vtkViewTheme_SetCellColor__SWIG_0(cast(void*)swigCPtr, _arg1, _arg2, _arg3);
  }

  public void SetCellColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_SetCellColor__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public double* GetCellColor() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetCellColor__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetCellColor(double* _arg1, double* _arg2, double* _arg3) {
    vtkd_im.vtkViewTheme_GetCellColor__SWIG_1(cast(void*)swigCPtr, cast(void*)_arg1, cast(void*)_arg2, cast(void*)_arg3);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetCellColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_GetCellColor__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public void SetCellOpacity(double _arg) {
    vtkd_im.vtkViewTheme_SetCellOpacity(cast(void*)swigCPtr, _arg);
  }

  public double GetCellOpacity() {
    auto ret = vtkd_im.vtkViewTheme_GetCellOpacity(cast(void*)swigCPtr);
    return ret;
  }

  public void SetCellHueRange(double mn, double mx) {
    vtkd_im.vtkViewTheme_SetCellHueRange__SWIG_0(cast(void*)swigCPtr, mn, mx);
  }

  public void SetCellHueRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_SetCellHueRange__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public double* GetCellHueRange() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetCellHueRange__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetCellHueRange(double* mn, double* mx) {
    vtkd_im.vtkViewTheme_GetCellHueRange__SWIG_1(cast(void*)swigCPtr, cast(void*)mn, cast(void*)mx);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetCellHueRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_GetCellHueRange__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public void SetCellSaturationRange(double mn, double mx) {
    vtkd_im.vtkViewTheme_SetCellSaturationRange__SWIG_0(cast(void*)swigCPtr, mn, mx);
  }

  public void SetCellSaturationRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_SetCellSaturationRange__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public double* GetCellSaturationRange() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetCellSaturationRange__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetCellSaturationRange(double* mn, double* mx) {
    vtkd_im.vtkViewTheme_GetCellSaturationRange__SWIG_1(cast(void*)swigCPtr, cast(void*)mn, cast(void*)mx);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetCellSaturationRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_GetCellSaturationRange__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public void SetCellValueRange(double mn, double mx) {
    vtkd_im.vtkViewTheme_SetCellValueRange__SWIG_0(cast(void*)swigCPtr, mn, mx);
  }

  public void SetCellValueRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_SetCellValueRange__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public double* GetCellValueRange() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetCellValueRange__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetCellValueRange(double* mn, double* mx) {
    vtkd_im.vtkViewTheme_GetCellValueRange__SWIG_1(cast(void*)swigCPtr, cast(void*)mn, cast(void*)mx);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetCellValueRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_GetCellValueRange__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public void SetCellAlphaRange(double mn, double mx) {
    vtkd_im.vtkViewTheme_SetCellAlphaRange__SWIG_0(cast(void*)swigCPtr, mn, mx);
  }

  public void SetCellAlphaRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_SetCellAlphaRange__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public double* GetCellAlphaRange() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetCellAlphaRange__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetCellAlphaRange(double* mn, double* mx) {
    vtkd_im.vtkViewTheme_GetCellAlphaRange__SWIG_1(cast(void*)swigCPtr, cast(void*)mn, cast(void*)mx);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetCellAlphaRange(SWIGTYPE_p_double.SWIGTYPE_p_double rng) {
    vtkd_im.vtkViewTheme_GetCellAlphaRange__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(rng));
  }

  public vtkScalarsToColors.vtkScalarsToColors GetCellLookupTable() {
    void* cPtr = vtkd_im.vtkViewTheme_GetCellLookupTable(cast(void*)swigCPtr);
    vtkScalarsToColors.vtkScalarsToColors ret = (cPtr is null) ? null : new vtkScalarsToColors.vtkScalarsToColors(cPtr, false);
    return ret;
  }

  public void SetCellLookupTable(vtkScalarsToColors.vtkScalarsToColors lut) {
    vtkd_im.vtkViewTheme_SetCellLookupTable(cast(void*)swigCPtr, vtkScalarsToColors.vtkScalarsToColors.swigGetCPtr(lut));
  }

  public void SetScaleCellLookupTable(bool _arg) {
    vtkd_im.vtkViewTheme_SetScaleCellLookupTable(cast(void*)swigCPtr, _arg);
  }

  public bool GetScaleCellLookupTable() {
    bool ret = vtkd_im.vtkViewTheme_GetScaleCellLookupTable(cast(void*)swigCPtr) ? true : false;
    return ret;
  }

  public void ScaleCellLookupTableOn() {
    vtkd_im.vtkViewTheme_ScaleCellLookupTableOn(cast(void*)swigCPtr);
  }

  public void ScaleCellLookupTableOff() {
    vtkd_im.vtkViewTheme_ScaleCellLookupTableOff(cast(void*)swigCPtr);
  }

  public void SetOutlineColor(double _arg1, double _arg2, double _arg3) {
    vtkd_im.vtkViewTheme_SetOutlineColor__SWIG_0(cast(void*)swigCPtr, _arg1, _arg2, _arg3);
  }

  public void SetOutlineColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_SetOutlineColor__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public double* GetOutlineColor() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetOutlineColor__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetOutlineColor(double* _arg1, double* _arg2, double* _arg3) {
    vtkd_im.vtkViewTheme_GetOutlineColor__SWIG_1(cast(void*)swigCPtr, cast(void*)_arg1, cast(void*)_arg2, cast(void*)_arg3);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetOutlineColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_GetOutlineColor__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public void SetSelectedPointColor(double _arg1, double _arg2, double _arg3) {
    vtkd_im.vtkViewTheme_SetSelectedPointColor__SWIG_0(cast(void*)swigCPtr, _arg1, _arg2, _arg3);
  }

  public void SetSelectedPointColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_SetSelectedPointColor__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public double* GetSelectedPointColor() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetSelectedPointColor__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetSelectedPointColor(double* _arg1, double* _arg2, double* _arg3) {
    vtkd_im.vtkViewTheme_GetSelectedPointColor__SWIG_1(cast(void*)swigCPtr, cast(void*)_arg1, cast(void*)_arg2, cast(void*)_arg3);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetSelectedPointColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_GetSelectedPointColor__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public void SetSelectedPointOpacity(double _arg) {
    vtkd_im.vtkViewTheme_SetSelectedPointOpacity(cast(void*)swigCPtr, _arg);
  }

  public double GetSelectedPointOpacity() {
    auto ret = vtkd_im.vtkViewTheme_GetSelectedPointOpacity(cast(void*)swigCPtr);
    return ret;
  }

  public void SetSelectedCellColor(double _arg1, double _arg2, double _arg3) {
    vtkd_im.vtkViewTheme_SetSelectedCellColor__SWIG_0(cast(void*)swigCPtr, _arg1, _arg2, _arg3);
  }

  public void SetSelectedCellColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_SetSelectedCellColor__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public double* GetSelectedCellColor() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetSelectedCellColor__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetSelectedCellColor(double* _arg1, double* _arg2, double* _arg3) {
    vtkd_im.vtkViewTheme_GetSelectedCellColor__SWIG_1(cast(void*)swigCPtr, cast(void*)_arg1, cast(void*)_arg2, cast(void*)_arg3);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetSelectedCellColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_GetSelectedCellColor__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public void SetSelectedCellOpacity(double _arg) {
    vtkd_im.vtkViewTheme_SetSelectedCellOpacity(cast(void*)swigCPtr, _arg);
  }

  public double GetSelectedCellOpacity() {
    auto ret = vtkd_im.vtkViewTheme_GetSelectedCellOpacity(cast(void*)swigCPtr);
    return ret;
  }

  public void SetBackgroundColor(double _arg1, double _arg2, double _arg3) {
    vtkd_im.vtkViewTheme_SetBackgroundColor__SWIG_0(cast(void*)swigCPtr, _arg1, _arg2, _arg3);
  }

  public void SetBackgroundColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_SetBackgroundColor__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public double* GetBackgroundColor() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetBackgroundColor__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetBackgroundColor(double* _arg1, double* _arg2, double* _arg3) {
    vtkd_im.vtkViewTheme_GetBackgroundColor__SWIG_1(cast(void*)swigCPtr, cast(void*)_arg1, cast(void*)_arg2, cast(void*)_arg3);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetBackgroundColor(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_GetBackgroundColor__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public void SetBackgroundColor2(double _arg1, double _arg2, double _arg3) {
    vtkd_im.vtkViewTheme_SetBackgroundColor2__SWIG_0(cast(void*)swigCPtr, _arg1, _arg2, _arg3);
  }

  public void SetBackgroundColor2(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_SetBackgroundColor2__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public double* GetBackgroundColor2() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetBackgroundColor2__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetBackgroundColor2(double* _arg1, double* _arg2, double* _arg3) {
    vtkd_im.vtkViewTheme_GetBackgroundColor2__SWIG_1(cast(void*)swigCPtr, cast(void*)_arg1, cast(void*)_arg2, cast(void*)_arg3);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetBackgroundColor2(SWIGTYPE_p_double.SWIGTYPE_p_double _arg) {
    vtkd_im.vtkViewTheme_GetBackgroundColor2__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(_arg));
  }

  public void SetPointTextProperty(vtkTextProperty.vtkTextProperty tprop) {
    vtkd_im.vtkViewTheme_SetPointTextProperty(cast(void*)swigCPtr, vtkTextProperty.vtkTextProperty.swigGetCPtr(tprop));
  }

  public vtkTextProperty.vtkTextProperty GetPointTextProperty() {
    void* cPtr = vtkd_im.vtkViewTheme_GetPointTextProperty(cast(void*)swigCPtr);
    vtkTextProperty.vtkTextProperty ret = (cPtr is null) ? null : new vtkTextProperty.vtkTextProperty(cPtr, false);
    return ret;
  }

  public void SetCellTextProperty(vtkTextProperty.vtkTextProperty tprop) {
    vtkd_im.vtkViewTheme_SetCellTextProperty(cast(void*)swigCPtr, vtkTextProperty.vtkTextProperty.swigGetCPtr(tprop));
  }

  public vtkTextProperty.vtkTextProperty GetCellTextProperty() {
    void* cPtr = vtkd_im.vtkViewTheme_GetCellTextProperty(cast(void*)swigCPtr);
    vtkTextProperty.vtkTextProperty ret = (cPtr is null) ? null : new vtkTextProperty.vtkTextProperty(cPtr, false);
    return ret;
  }

  public void SetVertexLabelColor(double r, double g, double b) {
    vtkd_im.vtkViewTheme_SetVertexLabelColor__SWIG_0(cast(void*)swigCPtr, r, g, b);
  }

  public void SetVertexLabelColor(SWIGTYPE_p_double.SWIGTYPE_p_double c) {
    vtkd_im.vtkViewTheme_SetVertexLabelColor__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(c));
  }

  public double* GetVertexLabelColor() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetVertexLabelColor__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetVertexLabelColor(double* r, double* g, double* b) {
    vtkd_im.vtkViewTheme_GetVertexLabelColor__SWIG_1(cast(void*)swigCPtr, cast(void*)r, cast(void*)g, cast(void*)b);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetVertexLabelColor(SWIGTYPE_p_double.SWIGTYPE_p_double c) {
    vtkd_im.vtkViewTheme_GetVertexLabelColor__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(c));
  }

  public void SetEdgeLabelColor(double r, double g, double b) {
    vtkd_im.vtkViewTheme_SetEdgeLabelColor__SWIG_0(cast(void*)swigCPtr, r, g, b);
  }

  public void SetEdgeLabelColor(SWIGTYPE_p_double.SWIGTYPE_p_double c) {
    vtkd_im.vtkViewTheme_SetEdgeLabelColor__SWIG_1(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(c));
  }

  public double* GetEdgeLabelColor() {
    auto ret = cast(double*)vtkd_im.vtkViewTheme_GetEdgeLabelColor__SWIG_0(cast(void*)swigCPtr);
    return ret;
  }

  public void GetEdgeLabelColor(double* r, double* g, double* b) {
    vtkd_im.vtkViewTheme_GetEdgeLabelColor__SWIG_1(cast(void*)swigCPtr, cast(void*)r, cast(void*)g, cast(void*)b);
    if (vtkd_im.SwigPendingException.isPending) throw vtkd_im.SwigPendingException.retrieve();
  }

  public void GetEdgeLabelColor(SWIGTYPE_p_double.SWIGTYPE_p_double c) {
    vtkd_im.vtkViewTheme_GetEdgeLabelColor__SWIG_2(cast(void*)swigCPtr, SWIGTYPE_p_double.SWIGTYPE_p_double.swigGetCPtr(c));
  }

  public static vtkViewTheme CreateOceanTheme() {
    void* cPtr = vtkd_im.vtkViewTheme_CreateOceanTheme();
    vtkViewTheme ret = (cPtr is null) ? null : new vtkViewTheme(cPtr, false);
    return ret;
  }

  public static vtkViewTheme CreateMellowTheme() {
    void* cPtr = vtkd_im.vtkViewTheme_CreateMellowTheme();
    vtkViewTheme ret = (cPtr is null) ? null : new vtkViewTheme(cPtr, false);
    return ret;
  }

  public static vtkViewTheme CreateNeonTheme() {
    void* cPtr = vtkd_im.vtkViewTheme_CreateNeonTheme();
    vtkViewTheme ret = (cPtr is null) ? null : new vtkViewTheme(cPtr, false);
    return ret;
  }

  public bool LookupMatchesPointTheme(vtkScalarsToColors.vtkScalarsToColors s2c) {
    bool ret = vtkd_im.vtkViewTheme_LookupMatchesPointTheme(cast(void*)swigCPtr, vtkScalarsToColors.vtkScalarsToColors.swigGetCPtr(s2c)) ? true : false;
    return ret;
  }

  public bool LookupMatchesCellTheme(vtkScalarsToColors.vtkScalarsToColors s2c) {
    bool ret = vtkd_im.vtkViewTheme_LookupMatchesCellTheme(cast(void*)swigCPtr, vtkScalarsToColors.vtkScalarsToColors.swigGetCPtr(s2c)) ? true : false;
    return ret;
  }
}
